In [1]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]
print(df.index)
print(df['category'].unique())
#df

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
               11,
            ...
            50446, 50447, 50448, 50449, 50450, 50451, 50452, 50453, 50454,
            50455],
           dtype='int64', length=42421)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']


In [2]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

42421
42421


In [3]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
482


In [4]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

305


In [5]:
#df[df['hashtag'].str.contains('โอเมก้า') == True]
#df[df['category']!= '']
df[df['category'].str.contains('Lovely|Secret') == False]
total = df['numOfchap'].sum()
print(total)
#df.dtypes
#df
#df[['title','hashtag','new_title','countTweet','countAccountReview','countHashReview','countRetweet','countFav']][df['hashtag'].str.contains('แด๊ดดี้') == True]
#df[df['title'].str.contains('เขาชื่ออันวาร์') == True]

390543.0


In [6]:
"""print(df['countTweet'].unique())
print(df['countHashReview'].unique())
print(df['countRetweet'].unique())
print(df['countFav'].unique())"""

"print(df['countTweet'].unique())\nprint(df['countHashReview'].unique())\nprint(df['countRetweet'].unique())\nprint(df['countFav'].unique())"

In [7]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

title  ratingNoTweet_q  \
0                       My boyfriend #แฟนน้องดุ             1.25   
1              Pre-order In Secret #เด็กคุณจ้าน             2.50   
2            ซุป\'ตาร์สิบแปดมงกุฎ #ใครกินวอดก้า             5.00   
3                    The Gentleman. #อาชัญอัยยา             1.25   
4                           #withlove : ด้วยรัก             1.25   
..                                          ...              ...   
767                   แฟนเด็กที่รัก.💚 #มาร์คกัน             5.00   
768      I\'m a baby red panda #ผมคือแพนด้าเด็ก             2.50   
769  Beauty And The Tattooist #โฉมงามกับช่างสัก             3.75   
770                           #ช่วงนี้เดือนหนาว             5.00   
771                       Happy New Year #วอนคิ             3.75   

     ratingHashReview_q  ratingFav_q  ratingRT_q  
0                   2.5          3.0         3.0  
1                   2.5          4.0         4.0  
2                   5.0          5.0         5.0  
3                   2.5          3.0         3.0  
4                   2.5          1.0         1.0  
..                  ...          ...         ...  
767                 2.5          5.0         5.0  
768                 2.5          2.0         2.0  
769                 2.5          5.0         5.0  
770                 2.5          5.0         5.0  
771                 2.5          2.0         3.0  

[772 rows x 5 columns]

In [8]:
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


In [9]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [10]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [11]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [12]:
#df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=False, duplicates = 'drop')
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
"""df['ratingLike_q'] = df['ratingLike_q'].replace(0.0,1.25)
df['ratingLike_q'] = df['ratingLike_q'].replace(1.0,2.5)
df['ratingLike_q'] = df['ratingLike_q'].replace(2.0,3.75)
df['ratingLike_q'] = df['ratingLike_q'].replace(3.0,5)"""

df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
#df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=False, duplicates = 'drop')
"""df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(0.0,1.25)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(1.0,2.5)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(2.0,3.75)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(3.0,5)"""

df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 3. 1.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
50451                                            ยั่วsex    2089          5.0   
50452  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
50453                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
50454                                           ร่านราคะ  122471        123.0   
50455           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
50451           3.0           3.0              2.0              2.0  
50452           3.0           4.0              4.0              4.0  
50453           2.0           3.0              2.0              3.0  
50454           5.0           5.0              5.0              5.0  
50455           1.0           2.0              1.0              2.0  

[42421 rows x 7 columns]

In [13]:
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q']][df['viewer'] == 3.0].sort_values(by='viewer', ascending = False).head(60) 
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q']][(df['viewer'] > 800) & (df['viewer'] < 1000)].sort_values(by='ratingCount',ascending = False)
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q','ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']].sort_values(by='ratingLike_q', ascending = False).head(5)

title  viewer  ratingCount  ratingView_q  \
0                   รอยรัก [yaoi ]   64455        147.0           5.0   
16552       [fic คริสสิง]Under RED   20143         73.0           5.0   
16516         ♡ รัก น้อง ตา หวาน ♡   33014        109.0           5.0   
16520  For Loved : ร้าย...เพราะรัก  133416        265.0           5.0   
16524             สัตวมาตา | MPREG   97317        193.0           5.0   

       ratingLike_q  ratingAdd2Fav_q  ratingComment_q  ratingHashReview_q  \
0               5.0              5.0              5.0                 0.0   
16552           5.0              4.0              5.0                 0.0   
16516           5.0              5.0              5.0                 0.0   
16520           5.0              5.0              5.0                 0.0   
16524           5.0              5.0              5.0                 0.0   

       ratingNoTweet_q  ratingRT_q  ratingFav_q  
0                  0.0         0.0          0.0  
16552              0.0         0.0          0.0  
16516              0.0         0.0          0.0  
16520              0.0         0.0          0.0  
16524              0.0         0.0          0.0

In [14]:
#Rating calculation
top = 88.0
w_LikeA = 78/top
w_LikeB = 25/top
w_View = 35/top
w_Add2Shelf = 88/top
w_Comment = 11/top
w_Tweet = 70/top
w_RT = 23/top
w_Fav = 17/top
w_Hash = 78/top

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
df101 = df
df101['101'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q) / 3).round(1)
df101 = df101.sort_values(by = ['101','favouriteCount'], ascending = False)
df101['101'].values[df101['101'].values < 1.0] = 1.0

df102 = df
df102['102'] = (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1) + (df.ratingComment_q * 0.88)) / (0.89+1.0+0.88)).round(1)
df102 = df102.sort_values(by = ['102','favouriteCount'], ascending = False)
df102['102'].values[df102['102'].values < 1.0] = 1.0

df111 = df
df111['111'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 6).round(1)
df111 = df111.sort_values(by = ['111','favouriteCount'], ascending = False)
df111['111'].values[df111['111'].values < 1.0] = 1.0

df112 = df
df112['112'] = (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1) + (df.ratingComment_q * 0.13) + (df.ratingHashReview_q * 0.89) + (df.ratingRT_q * 0.26) + (df.ratingFav_q * 0.19)) / (0.89+1.0+0.13+0.89+0.26+0.19)).round(1)
df112 = df112.sort_values(by = ['112','favouriteCount'], ascending = False)
df112['112'].values[df112['112'].values < 1.0] = 1.0

df121 = df
df121['121'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingNoTweet_q) / 4).round(1)
df121 = df121.sort_values(by = ['121','favouriteCount'], ascending = False)
df121['121'].values[df121['121'].values < 1.0] = 1.0

df122 = df
df122['122'] = (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1) + (df.ratingComment_q * 0.13) + (df.ratingNoTweet_q * 0.80)) / (0.89+1+0.13+0.80)).round(1)
df122 = df122.sort_values(by = ['122','favouriteCount'], ascending = False)
df122['122'].values[df122['122'].values < 1.0] = 1.0

df201 = df
df201['201'] = ((df.ratingLike_q+df.ratingView_q) / 2).round(1)
df201 = df201.sort_values(by = ['201','viewer'], ascending = False)
df201['201'].values[df201['201'].values < 1.0] = 1.0

df202 = df
df202['202'] = ((((df.ratingLike_q * 0.71) + (df.ratingView_q * 1.0))) / (0.71+1.0)).round(1)
df202 = df202.sort_values(by = ['202','viewer'], ascending = False)
df202['202'].values[df202['202'].values < 1.0] = 1.0

df211 = df
df211['211'] = ((df.ratingLike_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 5).round(1)
df211 = df211.sort_values(by = ['211','countHashReview'], ascending = False)
df211['211'].values[df211['211'].values < 1.0] = 1.0

df212 = df
df212['212'] = (((df.ratingLike_q * 0.32) + (df.ratingView_q * 0.45) + (df.ratingHashReview_q * 1.0) + (df.ratingRT_q * 0.29) + (df.ratingFav_q * 0.22)) / (0.32+0.45+1.0+0.29+0.22)).round(1)
df212 = df212.sort_values(by = ['212','countHashReview'], ascending = False)
df212['212'].values[df212['212'].values < 1.0] = 1.0

df221 = df
df221['221'] = ((df.ratingLike_q+df.ratingView_q+df.ratingNoTweet_q) / 3).round(1)
df221 = df221.sort_values(by = ['221','countTweet'], ascending = False)
df221['221'].values[df221['221'].values < 1.0] = 1.0

df222 = df
df222['222'] = (((df.ratingLike_q * 0.36) + (df.ratingView_q * 0.5) + (df.ratingNoTweet_q * 1.0)) / (0.36+0.5+1.0)).round(1)
df222 = df222.sort_values(by = ['222','countTweet'], ascending = False)
df222['222'].values[df222['222'].values < 1.0] = 1.0

df301 = df
df301['301'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingView_q) / 4).round(1)
df301 = df301.sort_values(by = ['301','favouriteCount'], ascending = False)
df301['301'].values[df301['301'].values < 1.0] = 1.0

df302A = df
df302A['302A'] = (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1.0) + (df.ratingComment_q * 0.13) + (df.ratingView_q * 0.4)) / (0.89+1.0+0.13+0.4)).round(1)
df302A = df302A.sort_values(by = ['302A','favouriteCount'], ascending = False)
df302A['302A'].values[df302A['302A'].values < 1.0] = 1.0

df302B = df
df302B['302B'] = (((df.ratingLike_q * 0.28) + (df.ratingAdd2Fav_q * 1.0) + (df.ratingComment_q * 0.13) + (df.ratingView_q * 0.4)) / (0.28+1.0+0.13+0.4)).round(1)
df302B = df302B.sort_values(by = ['302B','favouriteCount'], ascending = False)
df302B['302B'].values[df302B['302B'].values < 1.0] = 1.0

df311 = df
df311['311'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 7).round(1)
df311 = df311.sort_values(by = ['311','favouriteCount'], ascending = False)
df311['311'].values[df311['311'].values < 1.0] = 1.0

df312A = df
df312A['312A']= (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1.00) + (df.ratingView_q * 0.13) + (df.ratingComment_q * 0.40) + (df.ratingHashReview_q * 0.89) + (df.ratingRT_q * 0.26) + (df.ratingFav_q * 0.19)) / (0.89+1.00+0.13+0.4+0.89+0.26+0.19)).round(1)
df312A = df312A.sort_values(by = ['312A','favouriteCount'], ascending = False)
df312A['312A'].values[df312A['312A'].values < 1.0] = 1.0

df312B = df
df312B['312B'] = (((df.ratingLike_q * 0.28) + (df.ratingAdd2Fav_q * 1.0) + (df.ratingView_q * 0.13) + (df.ratingComment_q * 0.40) + (df.ratingHashReview_q * 0.89) + (df.ratingRT_q * 0.26) + (df.ratingFav_q * 0.19)) / (0.28+1.00+0.13+0.4+0.89+0.26+0.19)).round(1)
df312B = df312B.sort_values(by = ['312B','favouriteCount'], ascending = False)
df312B['312B'].values[df312B['312B'].values < 1.0] = 1.0

df321 = df
df321['321'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingNoTweet_q) / 5).round(1)
df321 = df321.sort_values(by = ['321','favouriteCount'], ascending = False)
df321['321'].values[df321['321'].values < 1.0] = 1.0

df322A = df
df322A['322A'] = (((df.ratingLike_q * 0.89) + (df.ratingAdd2Fav_q * 1.0) + (df.ratingView_q * 0.4) + (df.ratingComment_q * 0.13) + (df.ratingNoTweet_q * 0.8)) / (0.89+1.0+0.13+0.4+0.8)).round(1)
df322A = df322A.sort_values(by = ['322A','favouriteCount'], ascending = False)
df322A['322A'].values[df322A['322A'].values < 1.0] = 1.0

df322B = df
df322B['322B'] = (((df.ratingLike_q * 0.28) + (df.ratingAdd2Fav_q * 1.0) + (df.ratingView_q * 0.4) + (df.ratingComment_q * 0.13) + (df.ratingNoTweet_q * 0.8)) / (0.28+1.0+0.13+0.4+0.8)).round(1)
df322B = df322B.sort_values(by = ['322B','favouriteCount'], ascending = False)
df322B['322B'].values[df322B['322B'].values < 1.0] = 1.0

df011 = df
df011['011'] = ((df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 3).round(1)
df011 = df011.sort_values(by = ['011','countHashReview'], ascending = False)
df011['011'].values[df011['011'].values < 1.0] = 1.0


df012 = df
df012['012'] = (((df.ratingHashReview_q * 1.0) + (df.ratingRT_q * 0.29) + (df.ratingFav_q * 0.22)) / (1.0+0.29+0.22)).round(1)
df012 = df012.sort_values(by = ['012','countHashReview'], ascending = False)
df012['012'].values[df012['012'].values < 1.0] = 1.0

df021 = df
df021['021'] = df.ratingNoTweet_q
df021 = df021.sort_values(by = ['021','countTweet'], ascending = False)
df021['012'].values[df021['021'].values < 1.0] = 1.0


df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values[df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values < 1.0] = 1.0
df[['011','012','021']].values[df[['011','012','021']].values < 1.0] = 1.0

In [15]:
df101

author                    category  commentCount  \
48525  wickedwish_  นิยาย Boy Love Lovely Room       49555.0   
3991       oiimaps  นิยาย Boy Love Lovely Room       38644.0   
7820   White Demon  นิยาย Boy Love Lovely Room       45474.0   
18964     Jaylerqz  นิยาย Boy Love Secret Room       33058.0   
7778      D-Dindin  นิยาย Boy Love Lovely Room       99260.0   
...            ...                         ...           ...   
50393         Mind  นิยาย Boy Love Lovely Room           1.0   
50398         insa  นิยาย Boy Love Lovely Room           0.0   
50410      Sandy13  นิยาย Boy Love Lovely Room           0.0   
50445          可爱的  นิยาย Boy Love Lovely Room           0.0   
8215      น้องด๋อย  นิยาย Boy Love Lovely Room           0.0   

                                             description  favouriteCount  \
48525  จู่ๆเด็กนั่นก็โผล่มาตอนเที่ยงคืน บอกว่าผมเป็นห...         61242.0   
3991          "ไม่ดื้อกับพี่ได้ไหม" "ไม่ได้ ก็จะดื้อ!!"          50962.0   
7820   Omegaverse, Feel good, Futuristic fantasy, Sch...         50417.0   
18964  จันทราหาได้ประดับอยู่บนฟ้า เพราะเจ้าถูกดึงลงมา...         43788.0   
7778   องค์ชายสาม 'ฉีเยวี่ยน' ย้อนอดีตกลับมาเกิดใหม่เ...         41926.0   
...                                                  ...             ...   
50393  เคนชายผู้ถูกจากการตายของหมอทัศเขาจึงได้มีชีวิต...             0.0   
50398    เก็บโมเม้นสำหรับ JWA Condo Role Play Community              0.0   
50410             คุณเป็นสุข: นิยาย Boy Love Lovely Room             0.0   
50445  เป็น nc ที่ถูกคัดมานะคะ สามารถไปอ่านได้ในจอยค่...             0.0   
8215   ตั้งแต่ 'เปลี่ยนหัวใจ' มา ทำไมถึงได้เผลอคิดอะไ...            -7.0   

      isComplete  numOfchap  \
48525         จบ       35.0   
3991          จบ       33.0   
7820          จบ       56.0   
18964         จบ       42.0   
7778          จบ      106.0   
...          ...        ...   
50393         จบ        3.0   
50398         จบ        1.0   
50410         จบ        0.0   
50445         จบ        1.0   
8215          จบ        8.0   

                                                     pic  ratingCount  \
48525  https://cdn.readawrite.com/articles/1592/15911...      16294.0   
3991   https://cdn.readawrite.com/articles/1477/14762...      11639.0   
7820   https://cdn.readawrite.com/articles/876/875085...      13552.0   
18964  https://cdn.readawrite.com/articles/1931/19308...       8182.0   
7778   https://cdn.readawrite.com/articles/813/812472...      15410.0   
...                                                  ...          ...   
50393  https://cdn.readawrite.com/articles/1003/10021...          1.0   
50398  https://cdn.readawrite.com/articles/1035/10344...          0.0   
50410  https://cdn.readawrite.com/articles/1230/12297...          0.0   
50445  https://cdn.readawrite.com/articles/1446/14454...          0.0   
8215   https://cdn.readawrite.com/articles/230/229362...          0.0   

                                                     tag  ... countFav  \
48525                                                NaN  ...     2766   
3991                   omegaverse,oiimaps,ภาสตะนิด,Mpreg  ...    20290   
7820   Boy Love/Yaoi,โรงเรียน,นิยายวาย,นิยายแฟนตาซี,ต...  ...      793   
18964  นิยายวาย,Boy Love/Yaoi,ดราม่า,Mpreg,เจ้าพ่อ,JA...  ...     7170   
7778           Boy Love/Yaoi,นิยายจีนโบราณ,ฮาเร็ม,incest  ...     1533   
...                                                  ...  ...      ...   
50393                                                NaN  ...        0   
50398                                                NaN  ...        0   
50410              พี่คุณของเป็นสุข,น้องเป็นสุขของพี่คุณ  ...        0   
50445                  พี่แม่งน้องทัมจีม,นิยายรักวัยรุ่น  ...        0   
8215                              Boy Love/Yaoi,นิยายรัก  ...        0   

      ratingNoTweet_q  ratingHashReview_q ratingFav_q ratingRT_q  \
48525             5.0                 5.0         5.0        5.0   
3991              5.0                 5.0         5.0  

In [16]:
print(df['pic'])

0        https://cdn.readawrite.com/articles/451/450234...
1        https://cdn.readawrite.com/articles/451/450817...
2        https://cdn.readawrite.com/articles/460/459050...
3        https://cdn.readawrite.com/articles/460/459671...
4        https://cdn.readawrite.com/articles/465/464430...
                               ...                        
50451    https://cdn.readawrite.com/articles/1495/14946...
50452    https://cdn.readawrite.com/articles/1500/14999...
50453    https://cdn.readawrite.com/articles/1500/14999...
50454    https://cdn.readawrite.com/articles/1501/15002...
50455    https://cdn.readawrite.com/articles/1470/14691...
Name: pic, Length: 42421, dtype: object


In [17]:
df101.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\101.csv')
df102.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\102.csv')
df111.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\111.csv')
df112.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\112.csv')
df121.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\121.csv')
df122.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\122.csv')
df201.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\201.csv')
df202.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\202.csv')
df211.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\211.csv')
df212.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\212.csv')
df221.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\221.csv')
df222.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\222.csv')
df301.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\301.csv')
df302A.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\302A.csv')
df302B.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\302B.csv')
df311.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\311.csv')
df312A.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\312A.csv')
df312B.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\312B.csv')
df321.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\321.csv')
df322A.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\322A.csv')
df322B.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\322B.csv')
df011.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\011.csv')
df012.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\012.csv')
df021.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Evaluation\021.csv')

df.dtypes

author                 object
category               object
commentCount          float64
description            object
favouriteCount        float64
isComplete             object
numOfchap             float64
pic                    object
ratingCount           float64
tag                    object
title                  object
url                    object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
101                   float64
102                   float64
111                   float64
112                   float64
121                   float64
122       