In [1]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop(['Unnamed: 0','description','isComplete','numOfchap','pic','tag','url'], axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]

wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'], inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.index)
print(df['category'].unique())
df

RangeIndex(start=0, stop=41525, step=1)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']


author                    category commentCount favouriteCount  \
0      พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room          303            893   
1              ดองกี้  นิยาย Boy Love Secret Room          608          2,043   
2        มายเนมอิสธว.                  แฟนฟิคชั่น            0             11   
3           หมุขี้ชิป                  แฟนฟิคชั่น            5             13   
4            เธียรศกร  นิยาย Boy Love Lovely Room           16             65   
...               ...                         ...          ...            ...   
41520         โพธิ์ดำ  นิยาย Boy Love Lovely Room            6             18   
41521          jaynet  นิยาย Boy Love Lovely Room           44            119   
41522    แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room            7             19   
41523        ☻Gussi☽​  นิยาย Boy Love Secret Room          180          1,083   
41524              바이  นิยาย Boy Love Lovely Room            3              4   

      ratingCount                                              title   viewer  \
0             147                                     รอยรัก [yaoi ]   64,455   
1             306                                ล่ามรักรุ่นพี่ [จบ]  153,341   
2               0  Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...      267   
3               5                              คุณในห้วงคำนึง#แดนฮุน      264   
4               7                                            มาตะวัน   10,163   
...           ...                                                ...      ...   
41520         5.0                                            ยั่วsex    2,089   
41521        31.0  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1,943   
41522         5.0                            ใต้หล้านี้ข้าไฮเทค​สุด!      233   
41523       123.0                                           ร่านราคะ  122,471   
41524         2.0           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!      167   

                             new_title           hashtag  
0                                  NaN               NaN  
1                                  NaN               NaN  
2                                  NaN  ดอกไม้ของยากูซ่า  
3                       คุณในห้วงคำนึง               NaN  
4                              มาตะวัน               NaN  
...                                ...               ...  
41520                              NaN               NaN  
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก               NaN  
41522                              NaN               NaN  
41523                              NaN               NaN  
41524                              NaN               NaN  

[41525 rows x 9 columns]

In [2]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

41525
41525


In [3]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
482


In [4]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

305


In [5]:
#df[df['hashtag'].str.contains('โอเมก้า') == True]
#df[df['category']!= '']
df[df['category'].str.contains('Lovely|Secret') == False]
#total = df['numOfchap'].sum()
#print(total)
#df.dtypes
#df
#df[['title','hashtag','new_title','countTweet','countAccountReview','countHashReview','countRetweet','countFav']][df['hashtag'].str.contains('แด๊ดดี้') == True]
#df[df['title'].str.contains('เขาชื่ออันวาร์') == True]

author               category commentCount favouriteCount  \
2        มายเนมอิสธว.             แฟนฟิคชั่น            0             11   
3           หมุขี้ชิป             แฟนฟิคชั่น            5             13   
7      july-daisy-sun             แฟนฟิคชั่น            5             24   
12         mii_mikoto             แฟนฟิคชั่น         12.0             29   
14            RUBIXXX             แฟนฟิคชั่น         24.0             48   
...               ...                    ...          ...            ...   
30653           ŚiRIN             แฟนฟิคชั่น            9             25   
30656   เนี่ยหยางหลิน       นิยายรักจีนโบราณ            1             12   
30658        MirrorJK             แฟนฟิคชั่น            6             25   
30660          ที่สอง  นิยาย Girl Love/ Yuri          346            458   
30661      MinkCastle        นิยายรักวัยรุ่น            0              2   

      ratingCount                                              title  viewer  \
2               0  Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267   
3               5                              คุณในห้วงคำนึง#แดนฮุน     264   
7               5                      to dandelion you, | #ชบชาวไร่     548   
12           12.0  [FanFic BSG] บทสัมพาทษ์เฉพาะกิจ : ภาคโชโคคุ！！ ...   1,656   
14           23.0                         [DMBJ Fanfiction] 家 - Home   3,025   
...           ...                                                ...     ...   
30653         4.0                     -GRILL IN BLACK [reneseul rvv]     682   
30656           1                              หากจันทร์สิ้นแสง (BL)     358   
30658           3                                DEEP BLUE (#KAISOO)     304   
30660         129                      LIGHT BLUE #ข้างนอกฝนตกอยู่นะ  14,190   
30661           0                  Take\'s ME DOWN วายร้ายสายดื้อรัก      63   

               new_title            hashtag  countTweet  countAccountReview  \
2                    NaN   ดอกไม้ของยากูซ่า           0                   0   
3         คุณในห้วงคำนึง                NaN           0                   0   
7                    NaN           ชบชาวไร่           0                   0   
12                   NaN                NaN           0                   0   
14                   NaN                NaN           0                   0   
...                  ...                ...         ...                 ...   
30653                NaN                NaN           0                   0   
30656   หากจันทร์สิ้นแสง                NaN           0                   0   
30658                NaN                NaN           0                   0   
30660                NaN  ข้างนอกฝนตกอยู่นะ           0                   0   
30661  วายร้ายสายดื้อรัก                NaN           0                   0   

       countHashReview  countRetweet  countFav  
2                    0             0         0  
3                    0             0         0  
7                    0             0         0  
12                   0             0         0  
14                   0             0         0  
...                ...           ...       ...  
30653                0             0         0  
30656                0             0         0  
30658                0             0         0  
30660                0             0         0  
30661                0             0         0  

[9608 rows x 14 columns]

In [6]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

In [7]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [8]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [9]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [10]:
#df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=False, duplicates = 'drop')
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
"""df['ratingLike_q'] = df['ratingLike_q'].replace(0.0,1.25)
df['ratingLike_q'] = df['ratingLike_q'].replace(1.0,2.5)
df['ratingLike_q'] = df['ratingLike_q'].replace(2.0,3.75)
df['ratingLike_q'] = df['ratingLike_q'].replace(3.0,5)"""

df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
#df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=False, duplicates = 'drop')
"""df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(0.0,1.25)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(1.0,2.5)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(2.0,3.75)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(3.0,5)"""

df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 3. 1.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
41520                                            ยั่วsex    2089          5.0   
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
41522                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
41523                                           ร่านราคะ  122471        123.0   
41524           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
41520           3.0           3.0              2.0              2.0  
41521           3.0           4.0              4.0              4.0  
41522           2.0           3.0              3.0              3.0  
41523           5.0           5.0              5.0              5.0  
41524           1.0           2.0              1.0              2.0  

[41525 rows x 7 columns]

In [11]:
#Rating calculation
top = 88.0
w_LikeA = 78/top
w_LikeB = 25/top
w_View = 35/top
w_Add2Shelf = 88/top
w_Comment = 11/top
w_Tweet = 70/top
w_RT = 23/top
w_Fav = 17/top
w_Hash = 78/top

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
#model = ['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B','011','012','021']
model = ['1','2','3','4','5','6','7']
import os.path
from os import path
for i in range(len(model)):
    attr = 'df'+model[i]
    exec("%s = df" % attr)
df1['1'] = df.ratingView_q
df2['2'] = df.ratingLike_q
df3['3'] = df.ratingAdd2Fav_q
df4['4'] = df.ratingComment_q
df5['5'] = ((df.ratingView_q + df.ratingLike_q)/2.0).round(1)
df5['total5'] = df.viewer + df.ratingCount 
df6['6'] = ((df.ratingAdd2Fav_q + df.ratingLike_q + df.ratingComment_q)/3.0).round(1)
df6['total6'] = df.favouriteCount  + df.ratingCount + df.commentCount 
df7['7'] = ((df.ratingView_q+df.ratingAdd2Fav_q + df.ratingLike_q+df.ratingComment_q)/4.0).round(1)
df7['total7'] = df.viewer + df.favouriteCount  + df.ratingCount + df.commentCount


In [12]:
factor = ['viewer','ratingCount','favouriteCount','commentCount','ratingCount','favouriteCount','favouriteCount']
print(len(factor))
print(len(model))
folder = r'C:\Users\paton\Pick2ReadData\Rating\Evaluation'
for i in range(len(model)):
    #print(model[i])
    if model[i] < '5':
        exec("df%s = df%s.sort_values(by = ['%s','%s'], ascending = False)" % (model[i],model[i],model[i],factor[i]))
    else:
        exec("df%s = df%s.sort_values(by = ['%s','total%s'], ascending = False)" % (model[i],model[i],model[i],model[i]))
    exec("df%s['%s'].values[df%s['%s'].values < 1.0] = 1.0" % (model[i],model[i],model[i],model[i]))
    
for j in range(len(model)):
    model2 = ['1','2','3','4','5','6','7']
    exec("del model2[%s]" % j)
    exec("df%s.drop(model2, axis=1, inplace=True)" % model[j])
    if model[j] > '4':
        model3 = ['5','6','7']
        exec("model3.remove('%s')" % model3[j])
        exec("df%s.drop(model3, axis=1, inplace=True)" % (model[j],model[j]))
    #exec("df%s.to_csv(r'%s\Rating%s.csv')"%(model[j],folder,model[j]))
df.dtypes

7
7


author                 object
category               object
commentCount          float64
favouriteCount        float64
ratingCount           float64
title                  object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
1                     float64
2                     float64
3                     float64
4                     float64
5                     float64
total5                float64
6                     float64
total6                float64
7                     float64
total7                float64
dtype: object

In [13]:
print(df['1'][df['1'] == 5.0].count())
print(df['2'][df['2'] == 5.0].count())
print(df['3'][df['3'] == 5.0].count())
print(df['4'][df['4'] == 5.0].count())

8305
8251
8304
8276


In [14]:
#df.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\rating_v12.csv')
df6

author                    category  commentCount  \
5982                 D-Dindin  นิยาย Boy Love Lovely Room       99260.0   
3860   ซิงซิง ใครไม่ซิงเราซิง  นิยาย Boy Love Lovely Room       67087.0   
39640             wickedwish_  นิยาย Boy Love Lovely Room       49555.0   
9391                     คีย์  นิยาย Boy Love Secret Room       42729.0   
29234           กามเทพร้อยมุก  นิยาย Boy Love Lovely Room       45546.0   
...                       ...                         ...           ...   
38000                เด็กแว่น  นิยาย Boy Love Lovely Room           0.0   
22825                  chai.m          นิยายรักวัยว้าวุ่น           0.0   
38863           🖐🏻เบคอนเองคับ  นิยาย Boy Love Lovely Room           0.0   
38865                 LFinger  นิยาย Boy Love Lovely Room           0.0   
38881                  FORONG  นิยาย Boy Love Secret Room           0.0   

       favouriteCount  ratingCount  \
5982          41926.0      15410.0   
3860          38943.0      11082.0   
39640         61242.0      16294.0   
9391          16510.0       5117.0   
29234         35228.0      10884.0   
...               ...          ...   
38000             0.0          0.0   
22825             0.0          0.0   
38863             0.0          0.0   
38865             0.0          0.0   
38881             0.0          0.0   

                                                title   viewer  \
5982               องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)  7550855   
3860                 ชายาข้า ใครบังอาจหาญกล้ามาแตะ!!!  6007803   
39640  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า  5691482   
9391                The time to kill \"เกมรักอำมหิต\"  5334330   
29234       สามี ข้าจะปกป้องท่านเอง!(สนพ.บ้านวายบุ๊ค)  5065783   
...                                               ...      ...   
38000                                    กลิ่นต้นหญ้า        1   
22825                                 มีดเกี้ยวเกียร์        0   
38863                          อยู่นิ่งๆเดี๋ยวมันตื่น        0   
38865                           แม่ทัพเลี้ยงเด็ก (軍官)        0   
38881           time-line เส้นเวลาที่ไร้การเคลื่อนไหว        0   

                         new_title          hashtag  countTweet  ...  \
5982       องค์ชายสามช่างไม่เอาไหน              NaN          36  ...   
3860                           NaN              NaN           0  ...   
39640                          NaN  อย่าบอกป๊านะม๊า          80  ...   
9391                  เกมรักอำมหิต              NaN           0  ...   
29234                          NaN              NaN           0  ...   
...                            ...              ...         ...  ...   
38000                 กลิ่นต้นหญ้า              NaN           0  ...   
22825              มีดเกี้ยวเกียร์              NaN           0  ...   
38863       อยู่นิ่งๆเดี๋ยวมันตื่น              NaN           0  ...   
38865             แม่ทัพเลี้ยงเด็ก              NaN           0  ...   
38881  เส้นเวลาที่ไร้การเคลื่อนไหว              NaN           0  ...   

       ratingAdd2Fav_q    1    2    3    4    5     total5    6    7  \
5982               5.0  5.0  5.0  5.0  5.0  5.0  7566265.0  5.0  5.0   
3860               5.0  5.0  5.0  5.0  5.0  5.0  6018885.0  5.0  5.0   
39640              5.0  5.0  5.0  5.0  5.0  5.0  5707776.0  5.0  5.0   
9391               5.0  5.0  5.0  5.0  5.0  5.0  5339447.0  5.0  5.0   
29234              5.0  5.0  5.0  5.0  5.0  5.0  5076667.0  5.0  5.0   
...                ...  ...  ...  ...  ...  ...        ...  ...  ...   
38000              1.0  1.0  1.0  1.0  1.0  1.0        1.0  1.0  1.0   
22825              1.0  1.0  1.0  1.0  1.0  1.0        0.0  1.0  1.0   
38863              1.0  1.0  1.0  1.0  1.0  1.0        0.0  1.0  1.0   
38865              1.0  1.0  1.0  1.0  1.0  1.0        0.0  1.0  1.0   
38881              1.0  1.0  1.0  1.0  1.0  1.0        0.0  1.0  1.0   

           total7  
5982   15242896.0  
3860   12121636.0  
39640  11493761.0  
9391   10727899.0  
29234  10212340.0  
...           ...  
38