In [2]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
print(df.index)
#df

RangeIndex(start=0, stop=50456, step=1)


In [3]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

50456
50456


In [4]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
583


In [5]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

305


In [6]:
#df[df['hashtag'].str.contains('โอเมก้า') == True]
#df[df['category']!= '']
df[df['category'].str.contains('Lovely|Secret') == False]
total = df['numOfchap'].sum()
print(total)
#df.dtypes
#df
#df[['title','hashtag','new_title','countTweet','countAccountReview','countHashReview','countRetweet','countFav']][df['hashtag'].str.contains('แด๊ดดี้') == True]
#df[df['title'].str.contains('เขาชื่ออันวาร์') == True]

453058.0


In [7]:
"""print(df['countTweet'].unique())
print(df['countHashReview'].unique())
print(df['countRetweet'].unique())
print(df['countFav'].unique())"""

"print(df['countTweet'].unique())\nprint(df['countHashReview'].unique())\nprint(df['countRetweet'].unique())\nprint(df['countFav'].unique())"

In [8]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

title  ratingNoTweet_q  \
0                       My boyfriend #แฟนน้องดุ             1.25   
1              Pre-order In Secret #เด็กคุณจ้าน             2.50   
2            ซุป\'ตาร์สิบแปดมงกุฎ #ใครกินวอดก้า             5.00   
3                    The Gentleman. #อาชัญอัยยา             1.25   
4                    BNior — #คุณสีเทาบน [GOT7]             1.25   
..                                          ...              ...   
868                   แฟนเด็กที่รัก.💚 #มาร์คกัน             5.00   
869      I\'m a baby red panda #ผมคือแพนด้าเด็ก             2.50   
870  Beauty And The Tattooist #โฉมงามกับช่างสัก             3.75   
871                           #ช่วงนี้เดือนหนาว             5.00   
872                       Happy New Year #วอนคิ             3.75   

     ratingHashReview_q  ratingFav_q  ratingRT_q  
0                   2.5          3.0         3.0  
1                   2.5          4.0         4.0  
2                   5.0          5.0         5.0  
3                   2.5          3.0         3.0  
4                   2.5          3.0         3.0  
..                  ...          ...         ...  
868                 2.5          5.0         5.0  
869                 2.5          2.0         2.0  
870                 2.5          5.0         5.0  
871                 2.5          5.0         5.0  
872                 2.5          2.0         3.0  

[873 rows x 5 columns]

In [9]:
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


In [10]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [11]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [12]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [13]:
#df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=False, duplicates = 'drop')
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
"""df['ratingLike_q'] = df['ratingLike_q'].replace(0.0,1.25)
df['ratingLike_q'] = df['ratingLike_q'].replace(1.0,2.5)
df['ratingLike_q'] = df['ratingLike_q'].replace(2.0,3.75)
df['ratingLike_q'] = df['ratingLike_q'].replace(3.0,5)"""

df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
#df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=False, duplicates = 'drop')
"""df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(0.0,1.25)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(1.0,2.5)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(2.0,3.75)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(3.0,5)"""

df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 1. 3.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
50451                                            ยั่วsex    2089          5.0   
50452  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
50453                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
50454                                           ร่านราคะ  122471        123.0   
50455           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
50451           3.0           3.0              2.0              2.0  
50452           3.0           4.0              4.0              4.0  
50453           2.0           3.0              2.0              3.0  
50454           5.0           5.0              5.0              5.0  
50455           1.0           2.0              1.0              2.0  

[50456 rows x 7 columns]

In [14]:
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q']][df['viewer'] == 3.0].sort_values(by='viewer', ascending = False).head(60) 
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q']][(df['viewer'] > 800) & (df['viewer'] < 1000)].sort_values(by='ratingCount',ascending = False)
df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q','ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']].sort_values(by='ratingLike_q', ascending = False).head(5)

title   viewer  ratingCount  \
0                            รอยรัก [yaoi ]    64455        147.0   
33961    [rest] sweetest #สวีทไมล์ (jensoo)  1439200         63.0   
8875         [Mpreg] KILL MAFIA ♥ สัมผัสรัก   152715        188.0   
17931  this place is called \"THE JOESTAR\"     4708         64.0   
8877                     POINT OF NO RETURN    74364        231.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  \
0               5.0           5.0              5.0              5.0   
33961           5.0           5.0              4.0              5.0   
8875            5.0           5.0              5.0              5.0   
17931           4.0           5.0              4.0              4.0   
8877            5.0           5.0              5.0              5.0   

       ratingHashReview_q  ratingNoTweet_q  ratingRT_q  ratingFav_q  
0                     0.0              0.0         0.0          0.0  
33961                 0.0              0.0         0.0          0.0  
8875                  0.0              0.0         0.0          0.0  
17931                 0.0              0.0         0.0          0.0  
8877                  0.0              0.0         0.0          0.0

In [41]:
#Rating calculation
top = 88.0
w_LikeA = 78/top
w_LikeB = 25/top
w_View = 35/top
w_Add2Shelf = 88/top
w_Comment = 11/top
w_Tweet = 70/top
w_RT = 23/top
w_Fav = 17/top
w_Hash = 78/top

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q

df['101'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q) / 3).round(1)
df['102'] = (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingComment_q * w_Comment)) / (w_LikeA + w_Add2Shelf + w_Comment)).round(1)
df['111'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 6).round(1)
df['112'] = (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingComment_q * w_Comment) + (df.ratingHashReview_q * w_Hash) + (df.ratingRT_q * w_RT) + (df.ratingFav_q * w_Fav)) / (w_LikeA + w_Add2Shelf + w_Comment + w_Hash + w_RT + w_Fav)).round(1)
df['121'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingNoTweet_q) / 4).round(1)
df['122'] = (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingComment_q * w_Comment) + (df.ratingNoTweet_q * w_Tweet)) / (w_LikeA + w_Add2Shelf + w_Comment + w_Tweet)).round(1)
df['201'] = ((df.ratingLike_q+df.ratingView_q) / 2).round(1)
df['202'] = ((((df.ratingLike_q * w_LikeB) + (df.ratingView_q * w_View))) / (w_LikeB + w_View)).round(1)
df['211'] = ((df.ratingLike_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 5).round(1)
df['212'] = (((df.ratingLike_q * w_LikeB) + (df.ratingView_q * w_View) + (df.ratingHashReview_q * w_Hash) + (df.ratingRT_q * w_RT) + (df.ratingFav_q * w_Fav)) / (w_LikeB + w_View + w_Hash + w_RT + w_Fav)).round(1)
df['221'] = ((df.ratingLike_q+df.ratingView_q+df.ratingNoTweet_q) / 3).round(1)
df['222'] = (((df.ratingLike_q * w_LikeB) + (df.ratingView_q * w_View) + (df.ratingNoTweet_q * w_Tweet)) / (w_LikeB + w_View + w_Tweet)).round(1)
df['301'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingView_q) / 4).round(1)
df['302A'] = (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingComment_q * w_Comment) + (df.ratingView_q * w_View)) / (w_LikeA + w_Add2Shelf + w_Comment + w_View)).round(1)
df['302B'] = (((df.ratingLike_q * w_LikeB) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingComment_q * w_Comment) + (df.ratingView_q * w_View)) / (w_LikeB + w_Add2Shelf + w_Comment + w_View)).round(1)
df['311'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 7).round(1)
df['312A']= (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingView_q * w_View) + (df.ratingComment_q * w_Comment) + (df.ratingHashReview_q * w_Hash) + (df.ratingRT_q * w_RT) + (df.ratingFav_q * w_Fav)) / (w_LikeA + w_Add2Shelf + w_Comment + w_View + w_Hash + w_RT + w_Fav)).round(1)
df['312B'] = (((df.ratingLike_q * w_LikeB) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingView_q * w_View) + (df.ratingComment_q * w_Comment) + (df.ratingHashReview_q * w_Hash) + (df.ratingRT_q * w_RT) + (df.ratingFav_q * w_Fav)) / (w_LikeB + w_Add2Shelf + w_Comment + w_View + w_Hash + w_RT + w_Fav)).round(1)
df['321'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingNoTweet_q) / 5).round(1)
df['322A'] = (((df.ratingLike_q * w_LikeA) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingView_q * w_View) + (df.ratingComment_q * w_Comment) + (df.ratingNoTweet_q * w_Tweet)) / (w_LikeA + w_Add2Shelf + w_Comment + w_View + w_Tweet)).round(1)
df['322B'] = (((df.ratingLike_q * w_LikeB) + (df.ratingAdd2Fav_q * w_Add2Shelf) + (df.ratingView_q * w_View) + (df.ratingComment_q * w_Comment) + (df.ratingNoTweet_q * w_Tweet)) / (w_LikeB + w_Add2Shelf + w_Comment + w_View + w_Tweet)).round(1)

df['011'] = ((df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 3).round(1)
df['012'] = (((df.ratingHashReview_q * w_Hash) + (df.ratingRT_q * w_RT) + (df.ratingFav_q * w_Fav)) / (w_Hash + w_RT + w_Fav)).round(1)
df['021'] = df.ratingNoTweet_q

df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values[df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values < 1.0] = 1.0
df[['011','012','021']].values[df[['011','012','021']].values < 1.0] = 1.0

In [42]:
df

author                    category  commentCount  \
0      พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room         303.0   
1              ดองกี้  นิยาย Boy Love Secret Room         608.0   
2        มายเนมอิสธว.                  แฟนฟิคชั่น           0.0   
3           หมุขี้ชิป                  แฟนฟิคชั่น           5.0   
4            เธียรศกร  นิยาย Boy Love Lovely Room          16.0   
...               ...                         ...           ...   
50451         โพธิ์ดำ  นิยาย Boy Love Lovely Room           6.0   
50452          jaynet  นิยาย Boy Love Lovely Room          44.0   
50453    แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room           7.0   
50454        ☻Gussi☽​  นิยาย Boy Love Secret Room         180.0   
50455              바이  นิยาย Boy Love Lovely Room           3.0   

                                             description  favouriteCount  \
0      คำเตือน : เนื้อเรื่อง yaoi 18+ "เซสึนะ...เซสึน...           893.0   
1      ผมได้พี่มาง่ายๆแต่ผมไม่ปล่อยพี่ไปง่ายๆหรอกนะ เ...          2043.0   
2      ...ดอกไม้งามส่งกลิ่นหอม กลีบดอกบานสะพรั่ง แม้ก...            11.0   
3      การมีอยู่ของใครอีกคน รับรู้ทุกอย่างแต่สื่อไปไม...            13.0   
4      หนึ่งชายตามมาเพราะความรัก หนึ่งบุรุษจดจำรักมิไ...            65.0   
...                                                  ...             ...   
50451                                      มีรักมักมีsex            18.0   
50452  'ไว้ถึงตอนนั้นผมจะดูแลโนบิตะคุงตลอดไปครับ' #li...           119.0   
50453  เหตุเพราะตัวผมที่ลืมตามาอีกทีก็อยู่กลางป่าพร้อ...            19.0   
50454  *นิยายเรื่องนี้อาจมีการกระทำที่รุนแรง หยาบคาย ...          1083.0   
50455  อ่อไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่หรอรู...             4.0   

      isComplete  numOfchap  \
0             จบ       18.0   
1             จบ       35.0   
2             จบ        0.0   
3             จบ        0.0   
4             จบ       36.0   
...          ...        ...   
50451         จบ        2.0   
50452         จบ        4.0   
50453         จบ        0.0   
50454         จบ       10.0   
50455         จบ        2.0   

                                                     pic  ratingCount  \
0      https://cdn.readawrite.com/articles/451/450234...        147.0   
1      https://cdn.readawrite.com/articles/451/450817...        306.0   
2      https://cdn.readawrite.com/articles/460/459050...          0.0   
3      https://cdn.readawrite.com/articles/460/459671...          5.0   
4      https://cdn.readawrite.com/articles/465/464430...          7.0   
...                                                  ...          ...   
50451  https://cdn.readawrite.com/articles/1495/14946...          5.0   
50452  https://cdn.readawrite.com/articles/1500/14999...         31.0   
50453  https://cdn.readawrite.com/articles/1500/14999...          5.0   
50454  https://cdn.readawrite.com/articles/1501/15002...        123.0   
50455  https://cdn.readawrite.com/articles/1470/14691...          2.0   

                                                     tag  ... 302B  311  312A  \
0      นิยายวาย,ชายรักชาย,ป๊ะป๋า,โชตะ,Boy Love/Yaoi,Y...  ...  5.0  2.9   3.2   
1                    18+,Boy Love/Yaoi,วิศวะ,มหาวิทยาลัย  ...  5.0  2.9   3.2   
2                BTS,Fanfiction แฟนฟิคชั่น,Boy Love/Yaoi  ...  1.8  0.9   1.0   
3                    Boy Love/Yaoi,Fanfiction แฟนฟิคชั่น  ...  2.2  1.3   1.5   
4      นิยายวาย,ย้อนยุค,นิยายแฟนตาซี,Boy Love/Yaoi,นิ...  ...  3.8  2.0   2.3   
...                                                  ...  ...  ...  ...   ...   
50451                                                NaN  ...  2.4  1.4   1.6   
50452  listbyjaynet,เดคิสุงิ x โนบิตะ,โนบิตะ,เดคิโนบิ...  ...  3.8  2.1   2.5   
50453                                                NaN  ...  2.2  1.4   1.6   
50454                                 ร่าน,ผิดศีลธรรม,?p  ...  5.0  2.9   3.2   
50455                                                NaN  ...  1.2  0.9   0.9   

      312B  321  322A  322B  011  012  021  
0      2.9  4.0   3.8   3.5  

In [15]:
print(df['pic'])

0      https://cdn.readawrite.com/articles/1944/19436...
1      https://cdn.readawrite.com/articles/1944/19439...
2      https://cdn.readawrite.com/articles/1954/19538...
3      https://cdn.readawrite.com/articles/1955/19546...
4      https://cdn.readawrite.com/articles/1957/19568...
                             ...                        
376    https://cdn.readawrite.com/articles/307/306990...
377    https://cdn.readawrite.com/articles/385/384216...
378    https://cdn.readawrite.com/articles/407/406887...
379    https://cdn.readawrite.com/articles/390/389457...
380    https://cdn.readawrite.com/articles/397/396003...
Name: pic, Length: 1424, dtype: object


In [43]:
df.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\rating_v11.csv')
df.dtypes

author                 object
category               object
commentCount          float64
description            object
favouriteCount        float64
isComplete             object
numOfchap             float64
pic                    object
ratingCount           float64
tag                    object
title                  object
url                    object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
101                   float64
102                   float64
111                   float64
112                   float64
121                   float64
122       