In [1]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop('Unnamed: 0', axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]

wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'])
df.reset_index(drop=True, inplace=True)
print(df.index)
print(df['category'].unique())
df

RangeIndex(start=0, stop=42421, step=1)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']


author                    category commentCount  \
0      พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room          303   
1              ดองกี้  นิยาย Boy Love Secret Room          608   
2        มายเนมอิสธว.                  แฟนฟิคชั่น            0   
3           หมุขี้ชิป                  แฟนฟิคชั่น            5   
4            เธียรศกร  นิยาย Boy Love Lovely Room           16   
...               ...                         ...          ...   
42416         โพธิ์ดำ  นิยาย Boy Love Lovely Room            6   
42417          jaynet  นิยาย Boy Love Lovely Room           44   
42418    แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room            7   
42419        ☻Gussi☽​  นิยาย Boy Love Secret Room          180   
42420              바이  นิยาย Boy Love Lovely Room            3   

                                             description favouriteCount  \
0      คำเตือน : เนื้อเรื่อง yaoi 18+ "เซสึนะ...เซสึน...            893   
1      ผมได้พี่มาง่ายๆแต่ผมไม่ปล่อยพี่ไปง่ายๆหรอกนะ เ...          2,043   
2      ...ดอกไม้งามส่งกลิ่นหอม กลีบดอกบานสะพรั่ง แม้ก...             11   
3      การมีอยู่ของใครอีกคน รับรู้ทุกอย่างแต่สื่อไปไม...             13   
4      หนึ่งชายตามมาเพราะความรัก หนึ่งบุรุษจดจำรักมิไ...             65   
...                                                  ...            ...   
42416                                      มีรักมักมีsex             18   
42417  'ไว้ถึงตอนนั้นผมจะดูแลโนบิตะคุงตลอดไปครับ' #li...            119   
42418  เหตุเพราะตัวผมที่ลืมตามาอีกทีก็อยู่กลางป่าพร้อ...             19   
42419  *นิยายเรื่องนี้อาจมีการกระทำที่รุนแรง หยาบคาย ...          1,083   
42420  อ่อไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่หรอรู...              4   

      isComplete  numOfchap  \
0             จบ       18.0   
1             จบ       35.0   
2             จบ        0.0   
3             จบ        0.0   
4             จบ       36.0   
...          ...        ...   
42416         จบ        2.0   
42417         จบ        4.0   
42418         จบ        0.0   
42419         จบ       10.0   
42420         จบ        2.0   

                                                     pic ratingCount  \
0      https://cdn.readawrite.com/articles/451/450234...         147   
1      https://cdn.readawrite.com/articles/451/450817...         306   
2      https://cdn.readawrite.com/articles/460/459050...           0   
3      https://cdn.readawrite.com/articles/460/459671...           5   
4      https://cdn.readawrite.com/articles/465/464430...           7   
...                                                  ...         ...   
42416  https://cdn.readawrite.com/articles/1495/14946...         5.0   
42417  https://cdn.readawrite.com/articles/1500/14999...        31.0   
42418  https://cdn.readawrite.com/articles/1500/14999...         5.0   
42419  https://cdn.readawrite.com/articles/1501/15002...       123.0   
42420  https://cdn.readawrite.com/articles/1470/14691...         2.0   

                                                     tag  \
0      นิยายวาย,ชายรักชาย,ป๊ะป๋า,โชตะ,Boy Love/Yaoi,Y...   
1                    18+,Boy Love/Yaoi,วิศวะ,มหาวิทยาลัย   
2                BTS,Fanfiction แฟนฟิคชั่น,Boy Love/Yaoi   
3                    Boy Love/Yaoi,Fanfiction แฟนฟิคชั่น   
4      นิยายวาย,ย้อนยุค,นิยายแฟนตาซี,Boy Love/Yaoi,นิ...   
...                                                  ...   
42416                                                NaN   
42417  listbyjaynet,เดคิสุงิ x โนบิตะ,โนบิตะ,เดคิโนบิ...   
42418                                                NaN   
42419                                 ร่าน,ผิดศีลธรรม,?p   
42420                                                NaN   

                                                   title  \
0                                         รอยรัก [yaoi ]   
1                                    ล่ามรักรุ่นพี่ [จบ]   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...   
3                                  คุณในห้วงคำนึง#แดนฮุน   
4                                                มาตะวัน   
..

In [2]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

42421
42421


In [3]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
482


In [4]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

305


In [5]:
#df[df['hashtag'].str.contains('โอเมก้า') == True]
#df[df['category']!= '']
df[df['category'].str.contains('Lovely|Secret') == False]
total = df['numOfchap'].sum()
print(total)
#df.dtypes
#df
#df[['title','hashtag','new_title','countTweet','countAccountReview','countHashReview','countRetweet','countFav']][df['hashtag'].str.contains('แด๊ดดี้') == True]
#df[df['title'].str.contains('เขาชื่ออันวาร์') == True]

390543.0


In [6]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

In [7]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [8]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [9]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [10]:
#df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=False, duplicates = 'drop')
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
"""df['ratingLike_q'] = df['ratingLike_q'].replace(0.0,1.25)
df['ratingLike_q'] = df['ratingLike_q'].replace(1.0,2.5)
df['ratingLike_q'] = df['ratingLike_q'].replace(2.0,3.75)
df['ratingLike_q'] = df['ratingLike_q'].replace(3.0,5)"""

df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
#df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=False, duplicates = 'drop')
"""df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(0.0,1.25)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(1.0,2.5)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(2.0,3.75)
df['ratingAdd2Fav_q'] = df['ratingAdd2Fav_q'].replace(3.0,5)"""

df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 3. 1.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
42416                                            ยั่วsex    2089          5.0   
42417  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
42418                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
42419                                           ร่านราคะ  122471        123.0   
42420           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
42416           3.0           3.0              2.0              2.0  
42417           3.0           4.0              4.0              4.0  
42418           2.0           3.0              2.0              3.0  
42419           5.0           5.0              5.0              5.0  
42420           1.0           2.0              1.0              2.0  

[42421 rows x 7 columns]

In [11]:
#Rating calculation
top = 88.0
w_LikeA = 78/top
w_LikeB = 25/top
w_View = 35/top
w_Add2Shelf = 88/top
w_Comment = 11/top
w_Tweet = 70/top
w_RT = 23/top
w_Fav = 17/top
w_Hash = 78/top

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
model = ['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B','011','012','021']
import os.path
from os import path
for i in range(24):
    attr = 'df'+model[i]
    exec("%s = df" % attr)


df101['101'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q) / 3.0).round(1)

df102['102'] = (((df.ratingLike_q * 2) + (df.ratingAdd2Fav_q * 3) + (df.ratingComment_q * 1)) / (6.0)).round(1)

df111['111'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 6.0).round(1)

df112['112'] = (((df.ratingLike_q * 4) + (df.ratingAdd2Fav_q * 5) + (df.ratingComment_q * 1) + (df.ratingHashReview_q * 4) + (df.ratingRT_q * 3) + (df.ratingFav_q * 2)) / (19.0)).round(1)

df121['121'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingNoTweet_q) / 4).round(1)

df122['122'] = (((df.ratingLike_q * 3) + (df.ratingAdd2Fav_q * 4) + (df.ratingComment_q * 1) + (df.ratingNoTweet_q * 2)) / (10.0)).round(1)

df201['201'] = ((df.ratingLike_q+df.ratingView_q) / 2.0).round(1)

df202['202'] = ((((df.ratingLike_q * 1) + (df.ratingView_q * 2))) / (3.0)).round(1)

df211['211'] = ((df.ratingLike_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 5.0).round(1)

df212['212'] = (((df.ratingLike_q * 3) + (df.ratingView_q * 4) + (df.ratingHashReview_q * 5) + (df.ratingRT_q * 2) + (df.ratingFav_q * 1)) / (15.0)).round(1)

df221['221'] = ((df.ratingLike_q+df.ratingView_q+df.ratingNoTweet_q) / 3.0).round(1)

df222['222'] = (((df.ratingLike_q * 1) + (df.ratingView_q * 2) + (df.ratingNoTweet_q * 3)) / (6.0)).round(1)

df301['301'] = ((df.ratingLike_q+df.ratingAdd2Fav_q+df.ratingComment_q+df.ratingView_q) / 4.0).round(1)

df302A['302A'] = (((df.ratingLike_q * 3) + (df.ratingAdd2Fav_q * 4) + (df.ratingComment_q * 1) + (df.ratingView_q * 2)) / (10.0)).round(1)

df302B['302B'] = (((df.ratingLike_q * 2) + (df.ratingAdd2Fav_q * 4) + (df.ratingComment_q * 1) + (df.ratingView_q * 3)) / (10.0)).round(1)

df311['311'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingHashReview_q + df.ratingRT_q + df.ratingFav_q) / 7.0).round(1)

df312A['312A']= (((df.ratingLike_q * 5) + (df.ratingAdd2Fav_q * 6) + (df.ratingComment_q * 1) + (df.ratingView_q * 4) + (df.ratingHashReview_q * 5) + (df.ratingRT_q * 3) + (df.ratingFav_q * 2)) / (26.0)).round(1)

df312B['312B'] = (((df.ratingLike_q * 4) + (df.ratingAdd2Fav_q * 7) + (df.ratingComment_q * 1) + (df.ratingView_q * 5) + (df.ratingHashReview_q * 6) + (df.ratingRT_q * 3) + (df.ratingFav_q * 2)) / (28.0)).round(1)

df321['321'] = ((df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingView_q + df.ratingNoTweet_q) / 5.0).round(1)

df322A['322A'] = (((df.ratingLike_q * 4) + (df.ratingAdd2Fav_q * 5) + (df.ratingComment_q * 1) + (df.ratingView_q * 2) + (df.ratingNoTweet_q * 3)) / (15.0)).round(1)

df322B['322B'] = (((df.ratingLike_q * 2) + (df.ratingAdd2Fav_q * 5) + (df.ratingComment_q * 1) + (df.ratingView_q * 3)  + (df.ratingNoTweet_q * 4)) / (15.0)).round(1)

df011['011'] = ((df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q) / 3.0).round(1)

df012['012'] = (((df.ratingHashReview_q * 3) + (df.ratingRT_q * 2) + (df.ratingFav_q * 1)) / (6.0)).round(1)

df021['021'] = df.ratingNoTweet_q


df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values[df[['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B']].values < 1.0] = 1.0
df[['011','012','021']].values[df[['011','012','021']].values < 1.0] = 1.0

In [13]:
factor = ['favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','viewer','viewer','countHashReview','countHashReview','countTweet','countTweet','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','favouriteCount','countHashReview','countHashReview','countTweet']
model2 = ['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B','011','012','021']
print(len(factor))
print(len(model))
folder = r'C:\Users\paton\Pick2ReadData\Rating\Evaluation'
for i in range(24):
    #print(model[i])
    exec("df%s = df%s.sort_values(by = ['%s','%s'], ascending = False)" % (model[i],model[i],model[i],factor[i]))
    exec("df%s['%s'].values[df%s['%s'].values < 1.0] = 1.0" % (model[i],model[i],model[i],model[i]))
    #exec("df%s.to_csv(r'%s\Rating%s.csv')"%(model[i],folder,model[i]))
for j in range(24):
    model2 = ['101','102','111','112','121','122','201','202','211','212','221','222','301','302A','302B','311','312A','312B','321','322A','322B','011','012','021']
    exec("del model2[%s]" % j)
    exec("df%s.drop(model2, axis=1, inplace=True)" % model[j])
df.dtypes

24
24


author                 object
category               object
commentCount          float64
description            object
favouriteCount        float64
isComplete             object
numOfchap             float64
pic                    object
ratingCount           float64
tag                    object
title                  object
url                    object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
101                   float64
102                   float64
111                   float64
112                   float64
121                   float64
122       

In [14]:
df101[['title','101','favouriteCount']]

title  101  favouriteCount
40490  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า  5.0         61242.0
3284                           #ก็จะดื้อ (omegaverse)  5.0         50962.0
6473                        มหาลัยครึ่งมนุษย์ (ebook)  5.0         50417.0
15656                    รัตติจันทร์พันกร : ( Mpreg )  5.0         43788.0
6435               องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)  5.0         41926.0
...                                               ...  ...             ...
42358                                 นิทานจันทร์เพ็ญ  1.0             0.0
42363                                  Mew\'s Stories  1.0             0.0
42375                                      คุณเป็นสุข  1.0             0.0
42410                              พี่แม่ง น้องทัมจีม  1.0             0.0
6767   [YAOI] Change Innocent :: เปลี่ยนหัวใจมาเจอรัก  1.0            -7.0

[42421 rows x 3 columns]

In [16]:
df021

author                    category  commentCount  \
25862     summer december  นิยาย Boy Love Lovely Room        6968.0   
29428         Cinzano 505  นิยาย Boy Love Secret Room       24876.0   
39047                danw  นิยาย Boy Love Lovely Room           0.0   
15656            Jaylerqz  นิยาย Boy Love Secret Room       33058.0   
34920  นักเขียนฉบับแคดดี้  นิยาย Boy Love Lovely Room          73.0   
...                   ...                         ...           ...   
42416             โพธิ์ดำ  นิยาย Boy Love Lovely Room           6.0   
42417              jaynet  นิยาย Boy Love Lovely Room          44.0   
42418        แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room           7.0   
42419            ☻Gussi☽​  นิยาย Boy Love Secret Room         180.0   
42420                  바이  นิยาย Boy Love Lovely Room           3.0   

                                             description  favouriteCount  \
25862  งานแรกของ ‘พัท' อยู่ภายใต้การดูแลของ 'คุณเจ๋ง'...          8172.0   
29428  เขาเป็นคนสอนผมดื่มเหล้า สอนสูบบุหรี่ สอนกอด สอ...         31974.0   
39047  เรื่องราวระหว่างผมกับ'เขา'จุดเริ่มต้นของเรามัน...             1.0   
15656  จันทราหาได้ประดับอยู่บนฟ้า เพราะเจ้าถูกดึงลงมา...         43788.0   
34920  นิยายเรื่องนี้คล้ายๆซีรีย์ กลรักรุ่นพี่ แบบของ...           107.0   
...                                                  ...             ...   
42416                                      มีรักมักมีsex            18.0   
42417  'ไว้ถึงตอนนั้นผมจะดูแลโนบิตะคุงตลอดไปครับ' #li...           119.0   
42418  เหตุเพราะตัวผมที่ลืมตามาอีกทีก็อยู่กลางป่าพร้อ...            19.0   
42419  *นิยายเรื่องนี้อาจมีการกระทำที่รุนแรง หยาบคาย ...          1083.0   
42420  อ่อไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่หรอรู...             4.0   

      isComplete  numOfchap  \
25862         จบ       31.0   
29428         จบ       30.0   
39047         จบ        1.0   
15656         จบ       42.0   
34920         จบ        1.0   
...          ...        ...   
42416         จบ        2.0   
42417         จบ        4.0   
42418         จบ        0.0   
42419         จบ       10.0   
42420         จบ        2.0   

                                                     pic  ratingCount  \
25862  https://cdn.readawrite.com/articles/1630/16298...       1543.0   
29428  https://cdn.readawrite.com/articles/1898/18976...       6110.0   
39047  https://cdn.readawrite.com/articles/2460/24594...          0.0   
15656  https://cdn.readawrite.com/articles/1931/19308...       8182.0   
34920  https://cdn.readawrite.com/articles/1468/14673...         68.0   
...                                                  ...          ...   
42416  https://cdn.readawrite.com/articles/1495/14946...          5.0   
42417  https://cdn.readawrite.com/articles/1500/14999...         31.0   
42418  https://cdn.readawrite.com/articles/1500/14999...          5.0   
42419  https://cdn.readawrite.com/articles/1501/15002...        123.0   
42420  https://cdn.readawrite.com/articles/1470/14691...          2.0   

                                                     tag  ... countFav  \
25862  นิยายวาย,Slowburn,Agegap,enemiestolovers,Slow ...  ...    18229   
29428  Boy Love/Yaoi,นิยายรัก,นิยายโรแมนติก,friends w...  ...    11813   
39047                                                NaN  ...     2565   
15656  นิยายวาย,Boy Love/Yaoi,ดราม่า,Mpreg,เจ้าพ่อ,JA...  ...     7170   
34920                                                NaN  ...  1158022   
...                                                  ...  ...      ...   
42416                                                NaN  ...        0   
42417  listbyjaynet,เดคิสุงิ x โนบิตะ,โนบิตะ,เดคิโนบิ...  ...        0   
42418                                                NaN  ...        0   
42419                                 ร่าน,ผิดศีลธรรม,?p  ...        0   
42420                                                NaN  ...        0   

      ratingNoTweet_q  ratingHashReview_q ratingFav_q ratingRT_q  \
25862             5.0                 5.0     