In [1]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop(['Unnamed: 0','description','isComplete','numOfchap','tag','url'], axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]

wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'], inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.index)
print(df['category'].unique())
#df=df[df['title'].str.contains('ผมไหว้ล่ะ|ใครบังอาจหาญกล้า|ตัวนิดของคุณ|เกิดใหม่ทั้งทีมีแค่นี้?|Lost Love [ไร้ รัก]|อุบายกินรา|โอเมก้าตาบอด|ตัวร้ายต้องทำงานเหมือนกัน|เกิดใหม่อีกครั้งก็ยังห้าวไม่เลิก|เหนือมังกร เคียงบัล|เหนือจุดเยือกแข็ง|คุณสราญหาคู่|สามีนอกสมรส|คุณพฤกษ์รวยมาก|เมื่อยมทูตมาเดบิวต์เป็นไอดอล|คุณพระเอกที่กลายเป็นคนดี|มนัสวินทร์|อาการจะรัก that tiger|ผู้ชายที่เจอในแอปหาคู่คนนั้นรักจริงใช่ไหม|Cannon Fodder Cheat System|ไม้เรียวสีขาวกับเสื้อกาวน์เปื้อนชอล์ก|ทำไมเทพโอสถเช่นข้าต้องมาเกิดใหม่เป็นซัมมอนเนอร์|เล่ม 1]ฮ่องเต้เหตุใดท่านจึงงดงามเช่นนี้|เมื่อรู้ว่าเป็นต้นขาทองคำ|ไม่รักป๊าหรือม๊า|ชายาข้างามยิ่งนัก|สามีไม่โง่สามีแค่รักมาก|ฝนหลงฤดู') == True]
#name = 'ชายาข้า ใครบังอาจหาญกล้ามาแตะ|ผมไม่เป็น (Ω) ของคุณหรอก|เชิญแย่งพระเอกกันไปเถอะครับ|#อุบายกินรา|ตัวร้ายก็ต้องทำงานเหมือนกันนะ|คุณพฤกษ์รวยมาก|เกิดใหม่ทั้งทีมีแค่นี|เสือกินกวาง|สามีไม่โง่สามีแค่รักมาก|เหนือมังกร เคียงบัลลังก์|ผมไหว้ล่ะพี่ปี|เพียงคุณที่ผมคำนึง|คุณสราญหาคู่|ทะลุมิติไปเป็นเพื่อนสมัยเด็กของหวานใจในนิยาย|ก็จะดื้อ (omegaverse)|#ไม่รักป๊าหรือม๊า|สามีนอกสมรส|เมื่อยมทูตมาเดบิวต์เป็นไอดอล|ไยรักจึงอบอุ่นเพียงนี้|ตัวนิดของคุณใหญ่|วันนี้ท่านจอมพลก็ถูกหางของภรรยาเงือกฟาดหน้าอีกแล้ว|เจ้าของตะวัน|เลี่ยง หลิน|หนีผัวมาขายก๋วยจั๊บ|อาการจะรัก|ไอดอลซาตาน|ต้นขาทองคำก็จะขอกอดไว้|Love is Blue|เหนือจุดเยือกแข็ง|โอเมก้าตาบอด|บ้านหมีมีรัก|พันธะรักฤดูร้อน|ปลายธันวา|ระบบโกงชะตาตาย|มนัสวินทร์|สวัสดีครับ ผมมาแก้บน|ค่อยๆ รัก | #เจ๋งพัท'
#df = df[df.title.str.contains(name)]
print(df.index)
df

RangeIndex(start=0, stop=41525, step=1)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']
RangeIndex(start=0, stop=41525, step=1)


author                    category commentCount favouriteCount  \
0      พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room          303            893   
1              ดองกี้  นิยาย Boy Love Secret Room          608          2,043   
2        มายเนมอิสธว.                  แฟนฟิคชั่น            0             11   
3           หมุขี้ชิป                  แฟนฟิคชั่น            5             13   
4            เธียรศกร  นิยาย Boy Love Lovely Room           16             65   
...               ...                         ...          ...            ...   
41520         โพธิ์ดำ  นิยาย Boy Love Lovely Room            6             18   
41521          jaynet  นิยาย Boy Love Lovely Room           44            119   
41522    แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room            7             19   
41523        ☻Gussi☽​  นิยาย Boy Love Secret Room          180          1,083   
41524              바이  นิยาย Boy Love Lovely Room            3              4   

                                                     pic ratingCount  \
0      https://cdn.readawrite.com/articles/451/450234...         147   
1      https://cdn.readawrite.com/articles/451/450817...         306   
2      https://cdn.readawrite.com/articles/460/459050...           0   
3      https://cdn.readawrite.com/articles/460/459671...           5   
4      https://cdn.readawrite.com/articles/465/464430...           7   
...                                                  ...         ...   
41520  https://cdn.readawrite.com/articles/1495/14946...         5.0   
41521  https://cdn.readawrite.com/articles/1500/14999...        31.0   
41522  https://cdn.readawrite.com/articles/1500/14999...         5.0   
41523  https://cdn.readawrite.com/articles/1501/15002...       123.0   
41524  https://cdn.readawrite.com/articles/1470/14691...         2.0   

                                                   title   viewer  \
0                                         รอยรัก [yaoi ]   64,455   
1                                    ล่ามรักรุ่นพี่ [จบ]  153,341   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...      267   
3                                  คุณในห้วงคำนึง#แดนฮุน      264   
4                                                มาตะวัน   10,163   
...                                                  ...      ...   
41520                                            ยั่วsex    2,089   
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1,943   
41522                            ใต้หล้านี้ข้าไฮเทค​สุด!      233   
41523                                           ร่านราคะ  122,471   
41524           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!      167   

                             new_title           hashtag  
0                                  NaN               NaN  
1                                  NaN               NaN  
2                                  NaN  ดอกไม้ของยากูซ่า  
3                       คุณในห้วงคำนึง               NaN  
4                              มาตะวัน               NaN  
...                                ...               ...  
41520                              NaN               NaN  
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก               NaN  
41522                              NaN               NaN  
41523                              NaN               NaN  
41524                              NaN               NaN  

[41525 rows x 10 columns]

In [2]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

41525
41525


In [3]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
482


In [4]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

305


In [5]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,2)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,3)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,4)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

intweet['hash'] = inTweet[inTweet['countHashReview'] > 1.0]
inTweet['ratingHashReview_q'] = pd.qcut(inTweet['hash'], 3, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
#inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
#inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)
inTweet[inTweet['countHashReview'] == 0.0] = 1.0
inTweet[inTweet['countHashReview'] == 1.0] = 2.0

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

In [6]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [7]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [8]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [9]:
print('Website')
print('view and like : ' + str(df['viewer'].corr(df['ratingCount'])))
print('view and add to bookshelf : ' +str(df['viewer'].corr(df['favouriteCount'])))
print('view and comment : ' +str(df['viewer'].corr(df['commentCount'])))
print('like and add to bookshelf : ' +str(df['ratingCount'].corr(df['favouriteCount'])))
print('like and comment : ' +str(df['ratingCount'].corr(df['commentCount'])))
print('add to bookshelf and comment : ' +str(df['favouriteCount'].corr(df['commentCount'])))
print('\nTwitter')
dfCorr = df[df['countTweet'] > 0.0]
print('no tweet and RT : '+str(dfCorr['countTweet'].corr(dfCorr['countRetweet'])))
print('no tweet and Fav : '+str(dfCorr['countTweet'].corr(dfCorr['countFav'])))
print('no tweet and #แนะนำนิยาย : '+str(dfCorr['countTweet'].corr(dfCorr['countHashReview'])))
print('#แนะนำนิยาย and RT : '+str(dfCorr['countHashReview'].corr(dfCorr['countRetweet'])))
print('#แนะนำนิยาย and Fav : '+str(dfCorr['countHashReview'].corr(dfCorr['countFav'])))
print('RT and Fav : '+str(dfCorr['countRetweet'].corr(dfCorr['countFav'])))

print('\nWebsite and Twitter')
print('no tweet and view : '+str(dfCorr['countTweet'].corr(dfCorr['viewer'])))
print('no tweet and add to bookshelf : '+str(dfCorr['countTweet'].corr(dfCorr['favouriteCount'])))
print('no tweet and like : '+str(dfCorr['countTweet'].corr(dfCorr['ratingCount'])))
print('no tweet and comment : '+str(dfCorr['countTweet'].corr(dfCorr['commentCount'])))
print('')
print('retweet and view : '+str(dfCorr['countRetweet'].corr(dfCorr['viewer'])))
print('retweet and add to bookshelf : '+str(dfCorr['countRetweet'].corr(dfCorr['favouriteCount'])))
print('retweet and like : '+str(dfCorr['countRetweet'].corr(dfCorr['ratingCount'])))
print('retweet and comment : '+str(dfCorr['countRetweet'].corr(dfCorr['commentCount'])))
print('')
print('fav and view : '+str(dfCorr['countFav'].corr(dfCorr['viewer'])))
print('fav and add to bookshelf : '+str(dfCorr['countFav'].corr(dfCorr['favouriteCount'])))
print('fav and like : '+str(dfCorr['countFav'].corr(dfCorr['ratingCount'])))
print('fav and comment : '+str(dfCorr['countFav'].corr(dfCorr['commentCount'])))
print('')
print('fav and view : '+str(dfCorr['countHashReview'].corr(dfCorr['viewer'])))
print('fav and add to bookshelf : '+str(dfCorr['countHashReview'].corr(dfCorr['favouriteCount'])))
print('fav and like : '+str(dfCorr['countHashReview'].corr(dfCorr['ratingCount'])))
print('fav and comment : '+str(dfCorr['countHashReview'].corr(dfCorr['commentCount'])))

Website
view and like : 0.9201729325987775
view and add to bookshelf : 0.9011047976336266
view and comment : 0.9140068969050019
like and add to bookshelf : 0.9669282022058224
like and comment : 0.9366515406784068
add to bookshelf and comment : 0.861853536563523

Twitter
no tweet and RT : 0.36158518138492285
no tweet and Fav : 0.2360962381891951
no tweet and #แนะนำนิยาย : 0.30224383218638246
#แนะนำนิยาย and RT : 0.03441578265450749
#แนะนำนิยาย and Fav : -0.0034426738878812896
RT and Fav : 0.8174588838061119

Website and Twitter
no tweet and view : 0.09357071471303131
no tweet and add to bookshelf : 0.15540435403516428
no tweet and like : 0.12771529438045812
no tweet and comment : 0.1317436756547411

retweet and view : -0.013002294853006358
retweet and add to bookshelf : -0.01736285760950577
retweet and like : -0.012179695431024113
retweet and comment : -0.009766709008063297

fav and view : -0.015262483302619298
fav and add to bookshelf : -0.020906912148149947
fav and like : -0.015407081

In [10]:
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 3. 1.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
41520                                            ยั่วsex    2089          5.0   
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
41522                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
41523                                           ร่านราคะ  122471        123.0   
41524           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
41520           3.0           3.0              2.0              2.0  
41521           3.0           4.0              4.0              4.0  
41522           2.0           3.0              3.0              3.0  
41523           5.0           5.0              5.0              5.0  
41524           1.0           2.0              1.0              2.0  

[41525 rows x 7 columns]

In [11]:
#Rating calculation

df['Rating'] = ((df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingNoTweet_q)/4.0).round(1) 
df['total2_12'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet
df['Rating'].values[df['Rating'].values < 1.0] = 1.0
#df = df.sort_values(by = ['total2_12','Rating'], ascending = False)
#df.reset_index(drop=True, inplace=True)
df = df[['title', 'category','viewer','ratingCount','Rating','author','pic']]
df.dtypes

title           object
category        object
viewer           int64
ratingCount    float64
Rating         float64
author          object
pic             object
dtype: object

In [14]:
df

Title  \
0                                         รอยรัก [yaoi ]   
1                                    ล่ามรักรุ่นพี่ [จบ]   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...   
3                                  คุณในห้วงคำนึง#แดนฮุน   
4                                                มาตะวัน   
...                                                  ...   
41520                                            ยั่วsex   
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ   
41522                            ใต้หล้านี้ข้าไฮเทค​สุด!   
41523                                           ร่านราคะ   
41524           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!   

                         Category  View_R  Like_R  Rating          Author  \
0      นิยาย Boy Love Secret Room   64455   147.0     3.8  พ่อบ้านผู้นั้น   
1      นิยาย Boy Love Secret Room  153341   306.0     3.8          ดองกี้   
2                      แฟนฟิคชั่น     267     0.0     1.0    มายเนมอิสธว.   
3                      แฟนฟิคชั่น     264     5.0     1.8       หมุขี้ชิป   
4      นิยาย Boy Love Lovely Room   10163     7.0     2.5        เธียรศกร   
...                           ...     ...     ...     ...             ...   
41520  นิยาย Boy Love Lovely Room    2089     5.0     1.8         โพธิ์ดำ   
41521  นิยาย Boy Love Lovely Room    1943    31.0     3.0          jaynet   
41522  นิยาย Boy Love Lovely Room     233     5.0     2.2    แม่ค่ะหนูหิว   
41523  นิยาย Boy Love Secret Room  122471   123.0     3.8        ☻Gussi☽​   
41524  นิยาย Boy Love Lovely Room     167     2.0     1.2              바이   

                                                 Picture  
0      https://cdn.readawrite.com/articles/451/450234...  
1      https://cdn.readawrite.com/articles/451/450817...  
2      https://cdn.readawrite.com/articles/460/459050...  
3      https://cdn.readawrite.com/articles/460/459671...  
4      https://cdn.readawrite.com/articles/465/464430...  
...                                                  ...  
41520  https://cdn.readawrite.com/articles/1495/14946...  
41521  https://cdn.readawrite.com/articles/1500/14999...  
41522  https://cdn.readawrite.com/articles/1500/14999...  
41523  https://cdn.readawrite.com/articles/1501/15002...  
41524  https://cdn.readawrite.com/articles/1470/14691...  

[41525 rows x 7 columns]

In [13]:
df = df.rename(columns={" ": "No", "title": "Title", "pic": "Picture","author":"Author","ratingCount":"Like_R","viewer":"View_R","category":"Category"})
#df =df.head(10)

In [15]:
#df.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\RatingWeb_Top.csv')
df.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\RatingWeb.csv')