In [23]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop(['Unnamed: 0','description','isComplete','numOfchap','pic','tag','url'], axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]

wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'], inplace=True)

print(df.index)
print(df['category'].unique())
#df=df[df['title'].str.contains('ผมไหว้ล่ะ|ใครบังอาจหาญกล้า|ตัวนิดของคุณ|เกิดใหม่ทั้งทีมีแค่นี้?|Lost Love [ไร้ รัก]|อุบายกินรา|โอเมก้าตาบอด|ตัวร้ายต้องทำงานเหมือนกัน|เกิดใหม่อีกครั้งก็ยังห้าวไม่เลิก|เหนือมังกร เคียงบัล|เหนือจุดเยือกแข็ง|คุณสราญหาคู่|สามีนอกสมรส|คุณพฤกษ์รวยมาก|เมื่อยมทูตมาเดบิวต์เป็นไอดอล|คุณพระเอกที่กลายเป็นคนดี|มนัสวินทร์|อาการจะรัก that tiger|ผู้ชายที่เจอในแอปหาคู่คนนั้นรักจริงใช่ไหม|Cannon Fodder Cheat System|ไม้เรียวสีขาวกับเสื้อกาวน์เปื้อนชอล์ก|ทำไมเทพโอสถเช่นข้าต้องมาเกิดใหม่เป็นซัมมอนเนอร์|เล่ม 1]ฮ่องเต้เหตุใดท่านจึงงดงามเช่นนี้|เมื่อรู้ว่าเป็นต้นขาทองคำ|ไม่รักป๊าหรือม๊า|ชายาข้างามยิ่งนัก|สามีไม่โง่สามีแค่รักมาก|ฝนหลงฤดู') == True]
df.reset_index(drop=True, inplace=True)
df = df.head(9)
df

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
               11,
            ...
            50446, 50447, 50448, 50449, 50450, 50451, 50452, 50453, 50454,
            50455],
           dtype='int64', length=41525)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']


author                    category commentCount favouriteCount  \
0  พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room          303            893   
1          ดองกี้  นิยาย Boy Love Secret Room          608          2,043   
2    มายเนมอิสธว.                  แฟนฟิคชั่น            0             11   
3       หมุขี้ชิป                  แฟนฟิคชั่น            5             13   
4        เธียรศกร  นิยาย Boy Love Lovely Room           16             65   
5       Sonmonday  นิยาย Boy Love Lovely Room           28            210   
6    lovejinjunno  นิยาย Boy Love Lovely Room            1             17   
7  july-daisy-sun                  แฟนฟิคชั่น            5             24   
8           NIRIN  นิยาย Boy Love Lovely Room            4             14   

  ratingCount                                              title   viewer  \
0         147                                     รอยรัก [yaoi ]   64,455   
1         306                                ล่ามรักรุ่นพี่ [จบ]  153,341   
2           0  Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...      267   
3           5                              คุณในห้วงคำนึง#แดนฮุน      264   
4           7                                            มาตะวัน   10,163   
5          22                        My brother มันไม่ใช่พี่กู!!   17,978   
6           1                                     ด้วยแรงอธิษฐาน      718   
7           5                      to dandelion you, | #ชบชาวไร่      548   
8           4                                  พื้นที่ส่วนใจ [y]      460   

        new_title           hashtag  
0             NaN               NaN  
1             NaN               NaN  
2             NaN  ดอกไม้ของยากูซ่า  
3  คุณในห้วงคำนึง               NaN  
4         มาตะวัน               NaN  
5             NaN               NaN  
6  ด้วยแรงอธิษฐาน               NaN  
7             NaN          ชบชาวไร่  
8   พื้นที่ส่วนใจ               NaN

In [24]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

9
9
hashtag
0
0


In [25]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

ValueError: Bin edges must be unique: array([nan, nan, nan, nan, nan, nan]).
You can drop duplicate edges by setting the 'duplicates' kwarg

In [ ]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

In [ ]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

In [26]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [27]:
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 2. 4.]
[5. 1. 4. 3. 2.]
[5. 1. 2. 4.]
[5. 1. 4. 2. 3.]


title  viewer  ratingCount  \
0                                     รอยรัก [yaoi ]   64455          147   
1                                ล่ามรักรุ่นพี่ [จบ]  153341          306   
2  Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267            0   
3                              คุณในห้วงคำนึง#แดนฮุน     264            5   
4                                            มาตะวัน   10163            7   
5                        My brother มันไม่ใช่พี่กู!!   17978           22   
6                                     ด้วยแรงอธิษฐาน     718            1   
7                      to dandelion you, | #ชบชาวไร่     548            5   
8                                  พื้นที่ส่วนใจ [y]     460            4   

   ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0           5.0           5.0              5.0              5.0  
1           5.0           5.0              5.0              5.0  
2           1.0           1.0              1.0              1.0  
3           1.0           2.0              1.0              2.0  
4           4.0           4.0              4.0              4.0  
5           4.0           4.0              4.0              4.0  
6           3.0           1.0              2.0              1.0  
7           2.0           2.0              3.0              2.0  
8           2.0           2.0              2.0              2.0

In [8]:
#Rating calculation
w_View = 1
w_Like = 0.81
w_Add2Shelf = 0.92 
w_Comment = 0.11
w_Tweet = 1
w_Hash = 0.77
w_RT = 0.23
w_Fav = 0.17

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
model = ['W1_w','W2_w','W3_w','T1_w','W1T1_w','W2T1_w','W3T1_w','T2_w','W1T2_w','W2T2_w','W3T2_w','T3_w','W1T3_w','W2T3_w','W3T3_w']
import os.path
from os import path
for i in range(len(model)):
    exec("%s = df" % model[i])

W1_w['W1_w'] =  df.ratingView_q
W1_w['total1_1'] = df.viewer

W2_w['W2_w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment))/(w_Like+w_Add2Shelf+w_Comment)).round(1)
W2_w['total1_2'] = df.ratingCount + df.favouriteCount + df.commentCount

W3_w['W3_w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like) + (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment))/(w_View+w_Like+w_Add2Shelf+w_Comment)).round(1)
W3_w['total1_3'] =  df.viewer  + df.ratingCount + df.favouriteCount  + df.commentCount

T1_w['T1_w'] = df.ratingNoTweet_q
T1_w['total2_1'] = df.countTweet

W1T1_w['W1T1_w'] = (((df.ratingView_q*w_View) + (df.ratingNoTweet_q*w_Tweet))/(w_View+w_Tweet)).round(1) 
W1T1_w['total2_11'] = df.viewer + df.countTweet

W2T1_w['W2T1_w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf)  + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet))/(w_Like+w_Add2Shelf+w_Comment+w_Tweet)).round(1) 
W2T1_w['total2_12'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet

W3T1_w['W3T1_w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like) + (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingNoTweet_q*w_Tweet))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Tweet)).round(1) 
W3T1_w['total2_13'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet

T2_w['T2_w'] = (((df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Hash+w_RT+w_Fav)).round(1)
T2_w['total2_2'] = df.countHashReview+df.countRetweet+df.countFav

W1T2_w['W1T2_w'] = (((df.ratingView_q*w_View) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Hash+w_RT+w_Fav)).round(1) 
W1T2_w['total2_21'] = df.viewer + df.countHashReview+df.countRetweet+df.countFav

W2T2_w['W2T2_w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Like+w_Add2Shelf+w_Comment+w_Hash+w_RT+w_Fav)).round(1) 
W2T2_w['total2_22'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview + df.countRetweet + df.countFav

W3T2_w['W3T2_w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Hash+w_RT+w_Fav)).round(1) 
W3T2_w['total2_23'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview+df.countRetweet+df.countFav

T3_w['T3_w'] = (((df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Tweet+w_Hash+w_RT+w_Fav)).round(1)
T3_w['total2_3'] = df.countTweet+df.countHashReview+df.countRetweet+df.countFav

W1T3_w['W1T3_w'] = (((df.ratingView_q*w_View) + (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
W1T3_w['total2_31'] = df.viewer + +df.countTweet+df.countHashReview+df.countRetweet+df.countFav

W2T3_w['W2T3_w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Like+w_Add2Shelf+w_Comment+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
W2T3_w['total2_32'] =  df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet+ df.countHashReview + df.countRetweet + df.countFav

W3T3_w['W3T3_w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
W3T3_w['total2_33'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet + df.countHashReview+df.countRetweet+df.countFav

In [13]:
#factor = ['viewer','ratingCount','favouriteCount','commentCount','ratingCount','favouriteCount','favouriteCount']

factor = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
print(len(factor))
print(len(model))
folder = r'C:\Users\paton\Pick2ReadData\Rating\Evaluation'
#for i in range(len(model)):
#    #print(model[i])
#    exec("%s = %s.sort_values(by = ['%s','%s'], ascending = False)" % (model[i],model[i],model[i],factor[i]))
#    exec("%s['%s'].values[%s['%s'].values < 1.0] = 1.0" % (model[i],model[i],model[i],model[i]))
#    
#for j in range(len(model)):
#    model2 = ['rq1_1','rq1_2w','rq1_3w','rq2_1','rq2_11w','rq2_12w','rq2_13w','rq2_2w','rq2_21w','rq2_22w','rq2_23w','rq2_3w','rq2_31w','rq2_32w','rq2_33w']
#    factor2 = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
#    exec("del model2[%s]" % j)
#    exec("del factor2[%s]" % j)
#    exec("%s.drop(model2, axis=1, inplace=True)" % model[j])
#    exec("%s.drop(factor2, axis=1, inplace=True)" % model[j])
    #exec("%s.to_csv(r'%s\Rating%s.csv')"%(model[j],folder,model[j]))
#df.dtypes


15
15


In [15]:
for i in range(len(model)):
    exec("df['%s'].values[df['%s'].values < 1.0] = 1.0" % (model[i],model[i]))
    
df.sort_values(by = ['total2_12','W2T1_w'], ascending = False)
df.to_csv(r'C:\Users\paton\Pick2ReadData\Rating\Rating_w.csv')

In [ ]:
df
#df['rq2_1'][df['rq2_1'] == 0.0]