In [1]:
import pandas as pd
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop(['Unnamed: 0','description','isComplete','numOfchap','pic','tag','url'], axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]

wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'], inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.index)
print(df['category'].unique())
df

RangeIndex(start=0, stop=41525, step=1)
['นิยาย Boy Love Secret Room' 'แฟนฟิคชั่น' 'นิยาย Boy Love Lovely Room'
 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน' 'นิยายรักวัยว้าวุ่น' 'นิยายโรมานซ์'
 'นิยายรักจีนโบราณ' 'นิยาย Girl Love/ Yuri' 'นิยายรักสำหรับผู้ใหญ่'
 'วรรณกรรม/ดราม่า/เสียดสีสังคม' 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล' 'นิยายรัก'
 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน' 'นิยายรักวัยรุ่น']


author                    category commentCount favouriteCount  \
0      พ่อบ้านผู้นั้น  นิยาย Boy Love Secret Room          303            893   
1              ดองกี้  นิยาย Boy Love Secret Room          608          2,043   
2        มายเนมอิสธว.                  แฟนฟิคชั่น            0             11   
3           หมุขี้ชิป                  แฟนฟิคชั่น            5             13   
4            เธียรศกร  นิยาย Boy Love Lovely Room           16             65   
...               ...                         ...          ...            ...   
41520         โพธิ์ดำ  นิยาย Boy Love Lovely Room            6             18   
41521          jaynet  นิยาย Boy Love Lovely Room           44            119   
41522    แม่ค่ะหนูหิว  นิยาย Boy Love Lovely Room            7             19   
41523        ☻Gussi☽​  นิยาย Boy Love Secret Room          180          1,083   
41524              바이  นิยาย Boy Love Lovely Room            3              4   

      ratingCount                                              title   viewer  \
0             147                                     รอยรัก [yaoi ]   64,455   
1             306                                ล่ามรักรุ่นพี่ [จบ]  153,341   
2               0  Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...      267   
3               5                              คุณในห้วงคำนึง#แดนฮุน      264   
4               7                                            มาตะวัน   10,163   
...           ...                                                ...      ...   
41520         5.0                                            ยั่วsex    2,089   
41521        31.0  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1,943   
41522         5.0                            ใต้หล้านี้ข้าไฮเทค​สุด!      233   
41523       123.0                                           ร่านราคะ  122,471   
41524         2.0           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!      167   

                             new_title           hashtag  
0                                  NaN               NaN  
1                                  NaN               NaN  
2                                  NaN  ดอกไม้ของยากูซ่า  
3                       คุณในห้วงคำนึง               NaN  
4                              มาตะวัน               NaN  
...                                ...               ...  
41520                              NaN               NaN  
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก               NaN  
41522                              NaN               NaN  
41523                              NaN               NaN  
41524                              NaN               NaN  

[41525 rows x 9 columns]

In [2]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

41525
41525
hashtag
482
305


In [3]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=False, duplicates = 'drop')
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=False, duplicates = 'drop')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[1.25 2.5  5.   3.75]
[2.5 5. ]
[3. 4. 5. 1. 2.]
[3. 4. 5. 1. 2.]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexin

In [4]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [5]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [6]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [7]:
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[5. 1. 3. 4. 2.]
[5. 2. 4. 3. 1.]
[5. 1. 2. 3. 4.]
[5. 2. 4. 3. 1.]


title  viewer  ratingCount  \
0                                         รอยรัก [yaoi ]   64455        147.0   
1                                    ล่ามรักรุ่นพี่ [จบ]  153341        306.0   
2      Hachikusan No Hana 八 九 三の花 #ดอกไม้ของยากูซ่า [...     267          0.0   
3                                  คุณในห้วงคำนึง#แดนฮุน     264          5.0   
4                                                มาตะวัน   10163          7.0   
...                                                  ...     ...          ...   
41520                                            ยั่วsex    2089          5.0   
41521  ทฤษฎีเปลี่ยนนายให้กลายเป็นคนรัก | เดคิสุงิxโนบิตะ    1943         31.0   
41522                            ใต้หล้านี้ข้าไฮเทค​สุด!     233          5.0   
41523                                           ร่านราคะ  122471        123.0   
41524           ไอ้เจ๋งลูกอาแป๊ะที่ขายน้ำเต้าหู้ซอยสี่!!     167          2.0   

       ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0               5.0           5.0              5.0              5.0  
1               5.0           5.0              5.0              5.0  
2               2.0           1.0              2.0              1.0  
3               2.0           3.0              2.0              2.0  
4               4.0           3.0              4.0              3.0  
...             ...           ...              ...              ...  
41520           3.0           3.0              2.0              2.0  
41521           3.0           4.0              4.0              4.0  
41522           2.0           3.0              3.0              3.0  
41523           5.0           5.0              5.0              5.0  
41524           1.0           2.0              1.0              2.0  

[41525 rows x 7 columns]

In [13]:
#Rating calculation
w_View = 1
w_Like = 0.81
w_Add2Shelf = 0.92 
w_Comment = 0.11
w_Tweet = 1
w_Hash = 0.77
w_RT = 0.23
w_Fav = 0.17

#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
model = ['rq1_1','rq1_2w','rq1_3w','rq2_1','rq2_11w','rq2_12w','rq2_13w','rq2_2w','rq2_21w','rq2_22w','rq2_23w','rq2_3w','rq2_31w','rq2_32w','rq2_33w']
import os.path
from os import path
for i in range(len(model)):
    exec("%s = df" % model[i])

rq1_1['rq1_1'] =  df.ratingView_q
rq1_1['total1_1'] = df.viewer

rq1_2w['rq1_2w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment))/(w_Like+w_Add2Shelf+w_Comment)).round(1)
rq1_2w['total1_2'] = df.ratingCount + df.favouriteCount + df.commentCount

rq1_3w['rq1_3w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like) + (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment))/(w_View+w_Like+w_Add2Shelf+w_Comment)).round(1)
rq1_3w['total1_3'] =  df.viewer  + df.ratingCount + df.favouriteCount  + df.commentCount

rq2_1['rq2_1'] = df.ratingNoTweet_q
rq2_1['total2_1'] = df.countTweet

rq2_11w['rq2_11w'] = (((df.ratingView_q*w_View) + (df.ratingNoTweet_q*w_Tweet))/(w_View+w_Tweet)).round(1) 
rq2_11w['total2_11'] = df.viewer + df.countTweet

rq2_12w['rq2_12w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf)  + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet))/(w_Like+w_Add2Shelf+w_Comment+w_Tweet)).round(1) 
rq2_12w['total2_12'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet

rq2_13w['rq2_13w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like) + (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingNoTweet_q*w_Tweet))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Tweet)).round(1) 
rq2_13w['total2_13'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet

rq2_2w['rq2_2w'] = (((df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Hash+w_RT+w_Fav)).round(1)
rq2_2w['total2_2'] = df.countHashReview+df.countRetweet+df.countFav

rq2_21w['rq2_21w'] = (((df.ratingView_q*w_View) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Hash+w_RT+w_Fav)).round(1) 
rq2_21w['total2_21'] = df.viewer + df.countHashReview+df.countRetweet+df.countFav

rq2_22w['rq2_22w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Like+w_Add2Shelf+w_Comment+w_Hash+w_RT+w_Fav)).round(1) 
rq2_22w['total2_22'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview + df.countRetweet + df.countFav

rq2_23w['rq2_23w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment) + (df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Hash+w_RT+w_Fav)).round(1) 
rq2_23w['total2_23'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview+df.countRetweet+df.countFav

rq2_3w['rq2_3w'] = (((df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Tweet+w_Hash+w_RT+w_Fav)).round(1)
rq2_3w['total2_3'] = df.countTweet+df.countHashReview+df.countRetweet+df.countFav

rq2_31w['rq2_31w'] = (((df.ratingView_q*w_View) + (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
rq2_31w['total2_31'] = df.viewer + +df.countTweet+df.countHashReview+df.countRetweet+df.countFav

rq2_32w['rq2_32w'] = (((df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_Like+w_Add2Shelf+w_Comment+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
rq2_32w['total2_32'] =  df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet+ df.countHashReview + df.countRetweet + df.countFav

rq2_33w['rq2_33w'] = (((df.ratingView_q*w_View) + (df.ratingLike_q*w_Like)+ (df.ratingAdd2Fav_q*w_Add2Shelf) + (df.ratingComment_q*w_Comment)+ (df.ratingNoTweet_q*w_Tweet)+(df.ratingHashReview_q*w_Hash)+(df.ratingRT_q*w_RT)+(df.ratingFav_q*w_Fav))/(w_View+w_Like+w_Add2Shelf+w_Comment+w_Tweet+w_Hash+w_RT+w_Fav)).round(1) 
rq2_33w['total2_33'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet + df.countHashReview+df.countRetweet+df.countFav


In [14]:
#factor = ['viewer','ratingCount','favouriteCount','commentCount','ratingCount','favouriteCount','favouriteCount']
factor = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
print(len(factor))
print(len(model))
folder = r'C:\Users\paton\Pick2ReadData\Rating\Evaluation'
for i in range(len(model)):
    #print(model[i])
    exec("%s = %s.sort_values(by = ['%s','%s'], ascending = False)" % (model[i],model[i],model[i],factor[i]))
    exec("%s['%s'].values[%s['%s'].values < 1.0] = 1.0" % (model[i],model[i],model[i],model[i]))
    
for j in range(len(model)):
    model2 = ['rq1_1','rq1_2w','rq1_3w','rq2_1','rq2_11w','rq2_12w','rq2_13w','rq2_2w','rq2_21w','rq2_22w','rq2_23w','rq2_3w','rq2_31w','rq2_32w','rq2_33w']
    factor2 = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
    exec("del model2[%s]" % j)
    exec("del factor2[%s]" % j)
    exec("%s.drop(model2, axis=1, inplace=True)" % model[j])
    exec("%s.drop(factor2, axis=1, inplace=True)" % model[j])
    exec("%s.to_csv(r'%s\Rating%s.csv')"%(model[j],folder,model[j]))
df.dtypes

15
15


author                 object
category               object
commentCount          float64
favouriteCount        float64
ratingCount           float64
title                  object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
rq1_1                 float64
total1_1                int64
rq1_2w                float64
total1_2              float64
rq1_3w                float64
total1_3              float64
rq2_1                 float64
total2_1                int64
rq2_11w               float64
total2_11               int64
rq2_12w               float64
total2_12 

In [15]:
rq2_33w

author                    category  commentCount  \
5982        D-Dindin  นิยาย Boy Love Lovely Room       99260.0   
39640    wickedwish_  นิยาย Boy Love Lovely Room       49555.0   
6020     White Demon  นิยาย Boy Love Lovely Room       45474.0   
3280         oiimaps  นิยาย Boy Love Lovely Room       38644.0   
15178       Jaylerqz  นิยาย Boy Love Secret Room       33058.0   
...              ...                         ...           ...   
38000       เด็กแว่น  นิยาย Boy Love Lovely Room           0.0   
22825         chai.m          นิยายรักวัยว้าวุ่น           0.0   
38863  🖐🏻เบคอนเองคับ  นิยาย Boy Love Lovely Room           0.0   
38865        LFinger  นิยาย Boy Love Lovely Room           0.0   
38881         FORONG  นิยาย Boy Love Secret Room           0.0   

       favouriteCount  ratingCount  \
5982          41926.0      15410.0   
39640         61242.0      16294.0   
6020          50417.0      13552.0   
3280          50962.0      11639.0   
15178         43788.0       8182.0   
...               ...          ...   
38000             0.0          0.0   
22825             0.0          0.0   
38863             0.0          0.0   
38865             0.0          0.0   
38881             0.0          0.0   

                                                title   viewer  \
5982               องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)  7550855   
39640  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า  5691482   
6020                        มหาลัยครึ่งมนุษย์ (ebook)  4937046   
3280                           #ก็จะดื้อ (omegaverse)  3484456   
15178                    รัตติจันทร์พันกร : ( Mpreg )  3228236   
...                                               ...      ...   
38000                                    กลิ่นต้นหญ้า        1   
22825                                 มีดเกี้ยวเกียร์        0   
38863                          อยู่นิ่งๆเดี๋ยวมันตื่น        0   
38865                           แม่ทัพเลี้ยงเด็ก (軍官)        0   
38881           time-line เส้นเวลาที่ไร้การเคลื่อนไหว        0   

                         new_title          hashtag  countTweet  ...  \
5982       องค์ชายสามช่างไม่เอาไหน              NaN          36  ...   
39640                          NaN  อย่าบอกป๊านะม๊า          80  ...   
6020             มหาลัยครึ่งมนุษย์              NaN          26  ...   
3280                           NaN         ก็จะดื้อ         100  ...   
15178             รัตติจันทร์พันกร              NaN        1031  ...   
...                            ...              ...         ...  ...   
38000                 กลิ่นต้นหญ้า              NaN           0  ...   
22825              มีดเกี้ยวเกียร์              NaN           0  ...   
38863       อยู่นิ่งๆเดี๋ยวมันตื่น              NaN           0  ...   
38865             แม่ทัพเลี้ยงเด็ก              NaN           0  ...   
38881  เส้นเวลาที่ไร้การเคลื่อนไหว              NaN           0  ...   

       ratingNoTweet_q  ratingHashReview_q  ratingFav_q  ratingRT_q  \
5982               5.0                 5.0          5.0         5.0   
39640              5.0                 5.0          5.0         5.0   
6020               5.0                 5.0          5.0         4.0   
3280               5.0                 5.0          5.0         5.0   
15178              5.0                 5.0          5.0         5.0   
...                ...                 ...          ...         ...   
38000              0.0                 0.0          0.0         0.0   
22825              0.0                 0.0          0.0         0.0   
38863              0.0                 0.0          0.0         0.0   
38865              0.0                 0.0          0.0         0.0   
38881              0.0                 0.0          0.0         0.0   

       ratingLike_q  ratingComment_q  ratingView_q  ratingAdd2Fav_q  rq2_33w  \
5982            5.0              5.0           5.0              5.0      5.0   
39640           5.0              5.0           5.0              5.0      5.0   
6020         