In [15]:
import pandas as pd
df2 = pd.read_excel(r'D:\MUICT\Senior2020_Recommendation\Pick2Read\Pick2read conference\fiction.xlsx')
df2 = df2['0Fiction'].value_counts( ascending=False).head(20).keys().tolist()
df2.append('เมกาโลมา')
df2

['รัตติจันทร์พันกร',
 'midnight fortune #อย่าบอกป๊านะม๊า',
 'UNKNOWN LOVER #เขาชื่ออันวาร์',
 "I'll give you the world #เมกาโลมา",
 'มหาลัยครึ่งมนุษย์',
 '#ก็จะดื้อ',
 'ชายาข้า ใครบังอาจหาญกล้ามาแตะ!!!',
 'ตัวนิดของคุณใหญ่',
 '#วันดีวิทยา [S E T วิ ท ย า]',
 'My proposal #คุณ\u200bติอร่อยที่สุด',
 '#อุบายกินรา',
 'METANOIA #อรุณรุ่ง',
 'องค์ชายสามช่างไม่เอาไหน',
 'Deep Ocean #ฉลามคลั่งรัก',
 'เหนือมังกร เคียงบัลลังก์',
 'Your sky #กี่หมื่นฟ้า',
 'Cutie Pie นิ่งเฮียก็หาว่าซื่อ',
 'ค่อยๆ รัก #เจ๋งพัท',
 'เกิดใหม่ทั้งทีมีแค่นี้?',
 'MIDNIGHT FEI #ที่สุดของเฟย',
 'เมกาโลมา']

In [2]:
import numpy as np
import string

df = pd.read_csv(r'C:\Users\paton\readawrite_fiction2_BL.csv')
df.drop(['Unnamed: 0','description','isComplete','numOfchap','pic','tag','url'], axis=1, inplace=True)
df = df[(df['category'] == 'นิยาย Boy Love Secret Room') | (df['category'] == 'นิยาย Girl Love/ Yuri') | (df['category'] == 'นิยายรักสำหรับผู้ใหญ่') | (df['category'] == 'นิยายรัก')
       | (df['category'] == 'แฟนฟิคชั่น') | (df['category'] == 'นิยายโรมานซ์') | (df['category'] == 'นิยายแฟนตาซี/Sci-Fi/ไลท์โนเวล')
       | (df['category'] == 'นิยายผจญภัย/บู๊แอ็คชั่น/กำลังภายใน') | (df['category'] == 'นิยาย Boy Love Lovely Room') | (df['category'] == 'นิยายรักจีนโบราณ')
       | (df['category'] == 'นิยายลึกลับ/เขย่าขวัญ/สืบสวนสอบสวน') | (df['category'] == 'นิยายรักวัยรุ่น') | (df['category'] == 'นิยายรักวัยว้าวุ่น' )| (df['category'] == 'วรรณกรรม/ดราม่า/เสียดสีสังคม')]
df = df[df.title.str.contains('|'.join(df2), na=False)]
wordlist = '&#039;|&amp;|&bull;|&hearts;|&quot;|&lt;'
df_obj = df.select_dtypes(['object'])
df[df_obj.columns] = df_obj.apply(lambda x: x.str.strip())
df.drop_duplicates(subset=['title'], inplace=True)
df.reset_index(drop=True, inplace=True)
print(df.index)
print(df['category'].unique())
#df=df[df['title'].str.contains('ผมไหว้ล่ะ|ใครบังอาจหาญกล้า|ตัวนิดของคุณ|เกิดใหม่ทั้งทีมีแค่นี้?|Lost Love [ไร้ รัก]|อุบายกินรา|โอเมก้าตาบอด|ตัวร้ายต้องทำงานเหมือนกัน|เกิดใหม่อีกครั้งก็ยังห้าวไม่เลิก|เหนือมังกร เคียงบัล|เหนือจุดเยือกแข็ง|คุณสราญหาคู่|สามีนอกสมรส|คุณพฤกษ์รวยมาก|เมื่อยมทูตมาเดบิวต์เป็นไอดอล|คุณพระเอกที่กลายเป็นคนดี|มนัสวินทร์|อาการจะรัก that tiger|ผู้ชายที่เจอในแอปหาคู่คนนั้นรักจริงใช่ไหม|Cannon Fodder Cheat System|ไม้เรียวสีขาวกับเสื้อกาวน์เปื้อนชอล์ก|ทำไมเทพโอสถเช่นข้าต้องมาเกิดใหม่เป็นซัมมอนเนอร์|เล่ม 1]ฮ่องเต้เหตุใดท่านจึงงดงามเช่นนี้|เมื่อรู้ว่าเป็นต้นขาทองคำ|ไม่รักป๊าหรือม๊า|ชายาข้างามยิ่งนัก|สามีไม่โง่สามีแค่รักมาก|ฝนหลงฤดู') == True]
print(df.index)
df

RangeIndex(start=0, stop=15, step=1)
['นิยาย Boy Love Lovely Room' 'นิยาย Boy Love Secret Room']
RangeIndex(start=0, stop=15, step=1)


author                    category commentCount  \
0                 Jaylerqz  นิยาย Boy Love Lovely Room       22,809   
1                  oiimaps  นิยาย Boy Love Lovely Room       38,644   
2   ซิงซิง ใครไม่ซิงเราซิง  นิยาย Boy Love Lovely Room       67,087   
3                 D-Dindin  นิยาย Boy Love Lovely Room       99,260   
4              White Demon  นิยาย Boy Love Lovely Room       45,474   
5                Avery pie  นิยาย Boy Love Lovely Room        8,156   
6                 Jaylerqz  นิยาย Boy Love Secret Room       33,058   
7                     นทกร  นิยาย Boy Love Secret Room       16,852   
8            กระต่ายสีเงิน  นิยาย Boy Love Lovely Room       21,283   
9                     ละลิ  นิยาย Boy Love Lovely Room       16,005   
10             Cinzano 505  นิยาย Boy Love Secret Room       24,876   
11           กามเทพร้อยมุก  นิยาย Boy Love Lovely Room       41,747   
12           littlebbear96  นิยาย Boy Love Lovely Room        5,418   
13                  แบมแบม  นิยาย Boy Love Lovely Room       27,269   
14             wickedwish_  นิยาย Boy Love Lovely Room       49,555   

   favouriteCount ratingCount                                           title  \
0          30,887       8,109     I\'ll give you the world #เมกาโลมา (รีไรท์)   
1          50,962      11,639                          #ก็จะดื้อ (omegaverse)   
2          38,943      11,082                ชายาข้า ใครบังอาจหาญกล้ามาแตะ!!!   
3          41,926      15,410              องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)   
4          50,417      13,552                       มหาลัยครึ่งมนุษย์ (ebook)   
5          14,488       2,952            [END]Deep Ocean #ฉลามคลั่งรัก (YAOI)   
6          43,788       8,182                    รัตติจันทร์พันกร : ( Mpreg )   
7          24,932       5,218               METANOIA #อรุณรุ่ง [Omegaverse Ω]   
8          40,185       6,423                         เกิดใหม่ทั้งทีมีแค่นี้?   
9          40,913       6,425                ตัวนิดของคุณใหญ่ | BL-Omegaverse   
10         31,974       6,110                   UNKNOWN LOVER #เขาชื่ออันวาร์   
11         29,903       7,077       เหนือมังกร เคียงบัลลังก์(สนพ.บ้านวายบุ๊ค)   
12         15,327       2,441                #อุบายกินรา [YAOI] (สนพ. Hermit)   
13         39,654       9,878                   Cutie Pie นิ่งเฮียก็หาว่าซื่อ   
14         61,242      16,294  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า   

       viewer                new_title          hashtag  
0   3,787,353                      NaN         เมกาโลมา  
1   3,484,456                      NaN         ก็จะดื้อ  
2   6,007,803                      NaN              NaN  
3   7,550,855  องค์ชายสามช่างไม่เอาไหน              NaN  
4   4,937,046        มหาลัยครึ่งมนุษย์              NaN  
5   1,596,233                      NaN     ฉลามคลั่งรัก  
6   3,228,236         รัตติจันทร์พันกร              NaN  
7   1,389,025                      NaN         อรุณรุ่ง  
8   2,707,444   เกิดใหม่ทั้งทีมีแค่นี้              NaN  
9   1,684,507         ตัวนิดของคุณใหญ่              NaN  
10  2,177,987                      NaN   เขาชื่ออันวาร์  
11  3,903,986  เหนือมังกรเคียงบัลลังก์              NaN  
12    289,159                      NaN       อุบายกินรา  
13  2,655,776      นิ่งเฮียก็หาว่าซื่อ              NaN  
14  5,691,482                      NaN  อย่าบอกป๊านะม๊า

In [3]:
title = df['new_title'].tolist()
tfile = []
hashtag = df['hashtag'].tolist()
thfile = []
print(len(title))
print(len(hashtag))
for i in range(len(title)):
    name = '#'+str(title[i])+'.xlsx'
    name2= '#'+str(hashtag[i])+'.xlsx'
    tfile.append(name)
    thfile.append(name2) 
#print(tfile)
#print(thfile)

15
15


In [4]:
#hashtag
import os.path
from os import path
i = 0
count = 0
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Hashtag' 
noTweet = []
noAccountReview = []
noHashReview = []
noRetweet = []
noFav = []
for file in thfile:
    name = os.path.join(folder,file)
    #print(name)
    if path.exists(name): 
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (hashtag[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (hashtag[i],hashtag[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (hashtag[i]))
        exec("noTweet.append(len(%s.index))" % (hashtag[i]))
        exec("noRetweet.append(%s['retweet_count'].sum())" % (hashtag[i]))
        exec("noFav.append(%s['favourite_count'].sum())" % (hashtag[i]))
        exec("noAccountReview.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        exec("noHashReview.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (hashtag[i],hashtag[i]))
        count = count + 1
    else:
        noTweet.append(0)
        noAccountReview.append(0)
        noHashReview.append(0)
        noRetweet.append(0)
        noFav.append(0)
    i = i+1
df['countTweet'] = noTweet
df['countAccountReview'] = noAccountReview
df['countHashReview'] = noHashReview
df['countRetweet'] = noRetweet
df['countFav'] = noFav
print('hashtag')
print(count)

hashtag
6


In [5]:
#title
folder = 'C:/Users/paton/Downloads/twitter/Tweet1/Title' 
noTweet1 = []
noAccountReview1 = []
noHashReview1 = []
noRetweet1 = []
noFav1 = []
count1 = 0
for i in range(len(tfile)):
    name = os.path.join(folder,tfile[i])
    #print(name)
    #print(i)
    if path.exists(name):  
        #print(name)
        #print(hashtag[i])
        exec("%s = pd.read_excel('%s')" % (title[i],name))
        exec("%s['user_descriptions_owner'] = %s['user_descriptions_owner'].astype('object')" % (title[i],title[i]))
        exec("%s.drop('Unnamed: 0', axis=1, inplace=True)" % (title[i]))
        exec("noTweet1.append(len(%s.index))" % (title[i]))
        exec("noRetweet1.append(%s['retweet_count'].sum())" % (title[i]))
        exec("noFav1.append(%s['favourite_count'].sum())" % (title[i]))
        exec("noAccountReview1.append(len(%s[%s['user_descriptions_owner'].str.contains('แนะนำนิยาย|รีวิวนิยาย') == True]))" % (title[i],title[i]))
        exec("noHashReview1.append(len(%s[%s['text'].str.contains('#แนะนำนิยาย|#รีวิวนิยาย') == True]))" % (title[i],title[i]))
        count1 = count1 + 1
    else:
        noTweet1.append(0)
        noAccountReview1.append(0)
        noHashReview1.append(0)
        noRetweet1.append(0)
        noFav1.append(0)
df['countTweet1'] = noTweet1
df['countAccountReview1'] = noAccountReview1
df['countHashReview1'] = noHashReview1   
df['countRetweet1'] = noRetweet1
df['countFav1'] = noFav1


df['countTweet'] = df['countTweet'] + df['countTweet1']
df['countAccountReview'] = df['countAccountReview'] + df['countAccountReview1']
df['countHashReview'] = df['countHashReview'] + df['countHashReview1']
df['countRetweet'] = df['countRetweet'] + df['countRetweet1']
df['countFav'] = df['countFav'] + df['countFav1']

df.drop(['countTweet1','countAccountReview1','countHashReview1','countRetweet1','countFav1'], axis=1, inplace=True)

print(count1)

3


In [6]:
#Calculate rating for twitter
inTweet = df[df['countTweet'] > 0.0]
inTweet.reset_index(drop=True, inplace=True)

inTweet['ratingNoTweet_q'] = pd.qcut(inTweet['countTweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].astype('float64')

"""inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(0.0,1.25)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(1.0,2.5)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(2.0,3.75)
inTweet['ratingNoTweet_q'] = inTweet['ratingNoTweet_q'].replace(3.0,5)"""

inTweet['ratingHashReview_q'] = pd.qcut(inTweet['countHashReview'], 5, labels=[1,2,3,4,5])
inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].astype('float64')
#inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(0.0,2.5)
#inTweet['ratingHashReview_q'] = inTweet['ratingHashReview_q'].replace(1.0,5)

inTweet['ratingRT_q'] = pd.qcut(inTweet['countRetweet'], 5, labels=[1,2,3,4,5])
inTweet['ratingRT_q'] = inTweet['ratingRT_q'].astype('float64')

inTweet['ratingFav_q'] = pd.qcut(inTweet['countFav'], 5, labels=[1,2,3,4,5])
inTweet['ratingFav_q'] = inTweet['ratingFav_q'].astype('float64')

inTweet = inTweet[['title', 'ratingNoTweet_q', 'ratingHashReview_q','ratingFav_q','ratingRT_q']]
#inTweet[['countHashReview']][inTweet['countHashReview']>1.0].sort_values(by = 'countHashReview', ascending = False)
inTweet
print('q')
print(inTweet['ratingNoTweet_q'].unique())
print(inTweet['ratingHashReview_q'].unique())
print(inTweet['ratingRT_q'].unique())
print(inTweet['ratingFav_q'].unique())
#len(inTweet)

q
[2. 4. 1. 5. 3.]
[1. 4. 2. 5.]
[4. 5. 2. 1. 3.]
[4. 5. 2. 1. 3.]


D:\Anaconda\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexi

In [7]:
df = df.join(inTweet.set_index('title'), on='title', how='left')
df[['ratingHashReview_q','ratingNoTweet_q','ratingRT_q','ratingFav_q']][df['countTweet'] == 0.0] = 1.0
inTweet.dtypes

D:\Anaconda\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3059: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.iloc._setitem_with_indexer(indexer, value)
D:\Anaconda\lib\site-packages\pandas\core\frame.py:3037: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_array(key, v

title                  object
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
dtype: object

In [8]:
df['ratingNoTweet_q'] = df['ratingNoTweet_q'].fillna(0)
df['ratingHashReview_q'] = df['ratingHashReview_q'].fillna(0)
df['ratingRT_q'] = df['ratingRT_q'].fillna(0)
df['ratingFav_q'] = df['ratingFav_q'].fillna(0)
df[['title','countTweet','ratingNoTweet_q','ratingHashReview_q','ratingRT_q','ratingFav_q']].sort_values(by = 'ratingRT_q', ascending = False)
print("Because account review is not zero only 3")

Because account review is not zero only 3


In [9]:
#rating of website
df['ratingCount'] = df['ratingCount'].str.replace(',', '')
df['viewer'] = df['viewer'].str.replace(',', '')
df['favouriteCount'] = df['favouriteCount'].str.replace(',', '')
df['commentCount'] = df['commentCount'].str.replace(',', '')
df[['ratingCount', 'viewer','favouriteCount','commentCount']] = df[['ratingCount', 'viewer','favouriteCount','commentCount']].apply(pd.to_numeric)

In [10]:
print('Website')
print('view and like : ' + str(df['viewer'].corr(df['ratingCount'])))
print('view and add to bookshelf : ' +str(df['viewer'].corr(df['favouriteCount'])))
print('view and comment : ' +str(df['viewer'].corr(df['commentCount'])))
print('like and add to bookshelf : ' +str(df['ratingCount'].corr(df['favouriteCount'])))
print('like and comment : ' +str(df['ratingCount'].corr(df['commentCount'])))
print('add to bookshelf and comment : ' +str(df['favouriteCount'].corr(df['commentCount'])))
print('\nTwitter')
dfCorr = df[df['countTweet'] > 0.0]
print('no tweet and RT : '+str(dfCorr['countTweet'].corr(dfCorr['countRetweet'])))
print('no tweet and Fav : '+str(dfCorr['countTweet'].corr(dfCorr['countFav'])))
print('no tweet and #แนะนำนิยาย : '+str(dfCorr['countTweet'].corr(dfCorr['countHashReview'])))
print('#แนะนำนิยาย and RT : '+str(dfCorr['countHashReview'].corr(dfCorr['countRetweet'])))
print('#แนะนำนิยาย and Fav : '+str(dfCorr['countHashReview'].corr(dfCorr['countFav'])))
print('RT and Fav : '+str(dfCorr['countRetweet'].corr(dfCorr['countFav'])))

print('\nWebsite and Twitter')
print('no tweet and view : '+str(dfCorr['countTweet'].corr(dfCorr['viewer'])))
print('no tweet and add to bookshelf : '+str(dfCorr['countTweet'].corr(dfCorr['favouriteCount'])))
print('no tweet and like : '+str(dfCorr['countTweet'].corr(dfCorr['ratingCount'])))
print('no tweet and comment : '+str(dfCorr['countTweet'].corr(dfCorr['commentCount'])))
print('')
print('retweet and view : '+str(dfCorr['countRetweet'].corr(dfCorr['viewer'])))
print('retweet and add to bookshelf : '+str(dfCorr['countRetweet'].corr(dfCorr['favouriteCount'])))
print('retweet and like : '+str(dfCorr['countRetweet'].corr(dfCorr['ratingCount'])))
print('retweet and comment : '+str(dfCorr['countRetweet'].corr(dfCorr['commentCount'])))
print('')
print('fav and view : '+str(dfCorr['countFav'].corr(dfCorr['viewer'])))
print('fav and add to bookshelf : '+str(dfCorr['countFav'].corr(dfCorr['favouriteCount'])))
print('fav and like : '+str(dfCorr['countFav'].corr(dfCorr['ratingCount'])))
print('fav and comment : '+str(dfCorr['countFav'].corr(dfCorr['commentCount'])))
print('')
print('fav and view : '+str(dfCorr['countHashReview'].corr(dfCorr['viewer'])))
print('fav and add to bookshelf : '+str(dfCorr['countHashReview'].corr(dfCorr['favouriteCount'])))
print('fav and like : '+str(dfCorr['countHashReview'].corr(dfCorr['ratingCount'])))
print('fav and comment : '+str(dfCorr['countHashReview'].corr(dfCorr['commentCount'])))

Website
view and like : 0.8867150510173348
view and add to bookshelf : 0.6299325461274945
view and comment : 0.9445678202628041
like and add to bookshelf : 0.8577420954771716
like and comment : 0.8175368129478123
add to bookshelf and comment : 0.5282683101956387

Twitter
no tweet and RT : 0.45871726938345025
no tweet and Fav : 0.2663739160316584
no tweet and #แนะนำนิยาย : 0.007226240855237799
#แนะนำนิยาย and RT : -0.28496733056038065
#แนะนำนิยาย and Fav : -0.28299027847018504
RT and Fav : 0.9589347488878799

Website and Twitter
no tweet and view : -0.3410628831114342
no tweet and add to bookshelf : -0.14660814805288264
no tweet and like : -0.39423823509847883
no tweet and comment : -0.2604074480420634

retweet and view : -0.1969118858946219
retweet and add to bookshelf : 0.08617562047943117
retweet and like : -0.13902539546342899
retweet and comment : -0.18632389982028003

fav and view : -0.16450849301403575
fav and add to bookshelf : 0.15096593952113105
fav and like : -0.0809977256215

In [11]:
df['ratingLike_q'] = pd.qcut(df['ratingCount'], 5, labels=[1,2,3,4,5])
df['ratingComment_q'] = pd.qcut(df['commentCount'],5, labels=[1,2,3,4,5])
df['ratingView_q'] = pd.qcut(df['viewer'], 5, labels=[1,2,3,4,5])
df['ratingAdd2Fav_q'] = pd.qcut(df['favouriteCount'], 5, labels=[1,2,3,4,5])
df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] = df[['ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']].astype('float64')

#check
print(df['ratingLike_q'].unique())
print(df['ratingView_q'].unique())
print(df['ratingComment_q'].unique())
print(df['ratingAdd2Fav_q'].unique())

df[['title','viewer','ratingCount','ratingView_q','ratingLike_q','ratingAdd2Fav_q','ratingComment_q']] 

[3. 4. 5. 1. 2.]
[4. 3. 5. 1. 2.]
[2. 4. 5. 1. 3.]
[2. 5. 3. 4. 1.]


title   viewer  ratingCount  \
0      I\'ll give you the world #เมกาโลมา (รีไรท์)  3787353         8109   
1                           #ก็จะดื้อ (omegaverse)  3484456        11639   
2                 ชายาข้า ใครบังอาจหาญกล้ามาแตะ!!!  6007803        11082   
3               องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)  7550855        15410   
4                        มหาลัยครึ่งมนุษย์ (ebook)  4937046        13552   
5             [END]Deep Ocean #ฉลามคลั่งรัก (YAOI)  1596233         2952   
6                     รัตติจันทร์พันกร : ( Mpreg )  3228236         8182   
7                METANOIA #อรุณรุ่ง [Omegaverse Ω]  1389025         5218   
8                          เกิดใหม่ทั้งทีมีแค่นี้?  2707444         6423   
9                 ตัวนิดของคุณใหญ่ | BL-Omegaverse  1684507         6425   
10                   UNKNOWN LOVER #เขาชื่ออันวาร์  2177987         6110   
11       เหนือมังกร เคียงบัลลังก์(สนพ.บ้านวายบุ๊ค)  3903986         7077   
12                #อุบายกินรา [YAOI] (สนพ. Hermit)   289159         2441   
13                   Cutie Pie นิ่งเฮียก็หาว่าซื่อ  2655776         9878   
14  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า  5691482        16294   

    ratingView_q  ratingLike_q  ratingAdd2Fav_q  ratingComment_q  
0            4.0           3.0              2.0              2.0  
1            3.0           4.0              5.0              4.0  
2            5.0           4.0              3.0              5.0  
3            5.0           5.0              4.0              5.0  
4            4.0           5.0              5.0              4.0  
5            1.0           1.0              1.0              1.0  
6            3.0           3.0              4.0              3.0  
7            1.0           1.0              1.0              2.0  
8            3.0           2.0              3.0              2.0  
9            2.0           2.0              4.0              1.0  
10           2.0           2.0              2.0              3.0  
11           4.0           3.0              2.0              4.0  
12           1.0           1.0              1.0              1.0  
13           2.0           4.0              3.0              3.0  
14           5.0           5.0              5.0              5.0

In [12]:
#Rating calculation
#ratingView_q ratingLike_q ratingAdd2Fav_q ratingComment_q ratingHashReview_q ratingNoTweet_q ratingRT_q ratingFav_q
model = ['rq1_1','rq1_2','rq1_3','rq2_1','rq2_11','rq2_12','rq2_13','rq2_2','rq2_21','rq2_22','rq2_23','rq2_3','rq2_31','rq2_32','rq2_33']
import os.path
from os import path
for i in range(len(model)):
    exec("%s = df" % model[i])

rq1_1['rq1_1'] =  df.ratingView_q
rq1_1['total1_1'] = df.viewer
rq1_2['rq1_2'] = ((df.ratingLike_q+ df.ratingAdd2Fav_q  + df.ratingComment_q)/3.0).round(1)
rq1_2['total1_2'] = df.ratingCount + df.favouriteCount + df.commentCount
rq1_3['rq1_3'] = ((df.ratingView_q + df.ratingLike_q + df.ratingAdd2Fav_q + df.ratingComment_q)/4.0).round(1)
rq1_3['total1_3'] =  df.viewer  + df.ratingCount + df.favouriteCount  + df.commentCount

rq2_1['rq2_1'] = df.ratingNoTweet_q
rq2_1['total2_1'] = df.countTweet
rq2_11['rq2_11'] = ((df.ratingView_q + df.ratingNoTweet_q)/2.0).round(1) 
rq2_11['total2_11'] = df.viewer + df.countTweet
rq2_12['rq2_12'] = ((df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingNoTweet_q)/4.0).round(1) 
rq2_12['total2_12'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet
rq2_13['rq2_13'] = ((df.ratingView_q + df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingNoTweet_q)/5.0).round(1) 
rq2_13['total2_13'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countTweet

rq2_2['rq2_2'] = ((df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/3.0).round(1)
rq2_2['total2_2'] = df.countHashReview+df.countRetweet+df.countFav
rq2_21['rq2_21'] = ((df.ratingView_q + df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/4.0).round(1) 
rq2_21['total2_21'] = df.viewer + df.countHashReview+df.countRetweet+df.countFav
rq2_22['rq2_22'] = ((df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/6.0).round(1) 
rq2_22['total2_22'] =  df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview + df.countRetweet + df.countFav
rq2_23['rq2_23'] = ((df.ratingView_q + df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q + df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/7.0).round(1) 
rq2_23['total2_23'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount + df.countHashReview+df.countRetweet+df.countFav

rq2_3['rq2_3'] = ((df.ratingNoTweet_q+df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/4.0).round(1)
rq2_3['total2_3'] = df.countTweet+df.countHashReview+df.countRetweet+df.countFav
rq2_31['rq2_31'] = ((df.ratingView_q + df.ratingNoTweet_q +df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/5.0).round(1) 
rq2_31['total2_31'] = df.viewer + +df.countTweet+df.countHashReview+df.countRetweet+df.countFav
rq2_32['rq2_32'] = ((df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q  + df.ratingNoTweet_q + df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/7.0).round(1) 
rq2_32['total2_32'] =  df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet+ df.countHashReview + df.countRetweet + df.countFav
rq2_33['rq2_33'] = ((df.ratingView_q + df.ratingLike_q+ df.ratingAdd2Fav_q + df.ratingComment_q+ df.ratingNoTweet_q + df.ratingHashReview_q+df.ratingRT_q+df.ratingFav_q)/8.0).round(1) 
rq2_33['total2_33'] =  df.viewer + df.ratingCount + df.favouriteCount + df.commentCount +df.countTweet + df.countHashReview+df.countRetweet+df.countFav


In [13]:
#factor = ['viewer','ratingCount','favouriteCount','commentCount','ratingCount','favouriteCount','favouriteCount']
factor = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
print(len(factor))
print(len(model))
folder = r'C:\Users\paton\Pick2ReadData\Rating\Evaluation'
for i in range(len(model)):
    #print(model[i])
    exec("%s = %s.sort_values(by = ['%s','%s'], ascending = False)" % (model[i],model[i],model[i],factor[i]))
    exec("%s['%s'].values[%s['%s'].values < 1.0] = 1.0" % (model[i],model[i],model[i],model[i]))
    
for j in range(len(model)):
    model2 = ['rq1_1','rq1_2','rq1_3','rq2_1','rq2_11','rq2_12','rq2_13','rq2_2','rq2_21','rq2_22','rq2_23','rq2_3','rq2_31','rq2_32','rq2_33']
    factor2 = ['total1_1','total1_2','total1_3','total2_1','total2_11','total2_12','total2_13','total2_2','total2_21','total2_22','total2_23','total2_3','total2_31','total2_32','total2_33']
    exec("del model2[%s]" % j)
    exec("del factor2[%s]" % j)
    exec("%s.drop(model2, axis=1, inplace=True)" % model[j])
    exec("%s.drop(factor2, axis=1, inplace=True)" % model[j])
    #exec("%s.to_csv(r'%s\Rating%s.csv')"%(model[j],folder,model[j]))
df.dtypes

15
15


author                 object
category               object
commentCount            int64
favouriteCount          int64
ratingCount             int64
title                  object
viewer                  int64
new_title              object
hashtag                object
countTweet              int64
countAccountReview      int64
countHashReview         int64
countRetweet            int64
countFav                int64
ratingNoTweet_q       float64
ratingHashReview_q    float64
ratingFav_q           float64
ratingRT_q            float64
ratingLike_q          float64
ratingComment_q       float64
ratingView_q          float64
ratingAdd2Fav_q       float64
rq1_1                 float64
total1_1                int64
rq1_2                 float64
total1_2                int64
rq1_3                 float64
total1_3                int64
rq2_1                 float64
total2_1                int64
rq2_11                float64
total2_11               int64
rq2_12                float64
total2_12 

In [16]:
#
#rq1_3[['title','category']].head(15)
#rq1_1[rq1_1['title'].str.contains('ผมไหว้ล่ะ|ใครบังอาจหาญกล้า|ตัวนิดของคุณ|เกิดใหม่ทั้งทีมีแค่นี้?|Lost Love [ไร้ รัก]|อุบายกินรา|โอเมก้าตาบอด|ตัวร้ายต้องทำงานเหมือนกัน|เกิดใหม่อีกครั้งก็ยังห้าวไม่เลิก|เหนือมังกร เคียงบัล|เหนือจุดเยือกแข็ง|คุณสราญหาคู่|สามีนอกสมรส|คุณพฤกษ์รวยมาก|เมื่อยมทูตมาเดบิวต์เป็นไอดอล|คุณพระเอกที่กลายเป็นคนดี|มนัสวินทร์|อาการจะรัก that tiger|ผู้ชายที่เจอในแอปหาคู่คนนั้นรักจริงใช่ไหม|Cannon Fodder Cheat System|ไม้เรียวสีขาวกับเสื้อกาวน์เปื้อนชอล์ก|ทำไมเทพโอสถเช่นข้าต้องมาเกิดใหม่เป็นซัมมอนเนอร์|เล่ม 1]ฮ่องเต้เหตุใดท่านจึงงดงามเช่นนี้|เมื่อรู้ว่าเป็นต้นขาทองคำ|ไม่รักป๊าหรือม๊า|ชายาข้างามยิ่งนัก|สามีไม่โง่สามีแค่รักมาก|ฝนหลงฤดู') == True]
rq1_2.head(15)

author                    category  commentCount  \
14             wickedwish_  นิยาย Boy Love Lovely Room         49555   
3                 D-Dindin  นิยาย Boy Love Lovely Room         99260   
4              White Demon  นิยาย Boy Love Lovely Room         45474   
1                  oiimaps  นิยาย Boy Love Lovely Room         38644   
2   ซิงซิง ใครไม่ซิงเราซิง  นิยาย Boy Love Lovely Room         67087   
6                 Jaylerqz  นิยาย Boy Love Secret Room         33058   
13                  แบมแบม  นิยาย Boy Love Lovely Room         27269   
11           กามเทพร้อยมุก  นิยาย Boy Love Lovely Room         41747   
8            กระต่ายสีเงิน  นิยาย Boy Love Lovely Room         21283   
9                     ละลิ  นิยาย Boy Love Lovely Room         16005   
10             Cinzano 505  นิยาย Boy Love Secret Room         24876   
0                 Jaylerqz  นิยาย Boy Love Lovely Room         22809   
7                     นทกร  นิยาย Boy Love Secret Room         16852   
5                Avery pie  นิยาย Boy Love Lovely Room          8156   
12           littlebbear96  นิยาย Boy Love Lovely Room          5418   

    favouriteCount  ratingCount  \
14           61242        16294   
3            41926        15410   
4            50417        13552   
1            50962        11639   
2            38943        11082   
6            43788         8182   
13           39654         9878   
11           29903         7077   
8            40185         6423   
9            40913         6425   
10           31974         6110   
0            30887         8109   
7            24932         5218   
5            14488         2952   
12           15327         2441   

                                             title   viewer  \
14  (omegaverse) midnight fortune #อย่าบอกป๊านะม๊า  5691482   
3               องค์ชายสามช่างไม่เอาไหน (สนพ.ฟาไฉ)  7550855   
4                        มหาลัยครึ่งมนุษย์ (ebook)  4937046   
1                           #ก็จะดื้อ (omegaverse)  3484456   
2                 ชายาข้า ใครบังอาจหาญกล้ามาแตะ!!!  6007803   
6                     รัตติจันทร์พันกร : ( Mpreg )  3228236   
13                   Cutie Pie นิ่งเฮียก็หาว่าซื่อ  2655776   
11       เหนือมังกร เคียงบัลลังก์(สนพ.บ้านวายบุ๊ค)  3903986   
8                          เกิดใหม่ทั้งทีมีแค่นี้?  2707444   
9                 ตัวนิดของคุณใหญ่ | BL-Omegaverse  1684507   
10                   UNKNOWN LOVER #เขาชื่ออันวาร์  2177987   
0      I\'ll give you the world #เมกาโลมา (รีไรท์)  3787353   
7                METANOIA #อรุณรุ่ง [Omegaverse Ω]  1389025   
5             [END]Deep Ocean #ฉลามคลั่งรัก (YAOI)  1596233   
12                #อุบายกินรา [YAOI] (สนพ. Hermit)   289159   

                  new_title          hashtag  countTweet  ...  \
14                      NaN  อย่าบอกป๊านะม๊า          80  ...   
3   องค์ชายสามช่างไม่เอาไหน              NaN          36  ...   
4         มหาลัยครึ่งมนุษย์              NaN          26  ...   
1                       NaN         ก็จะดื้อ         100  ...   
2                       NaN              NaN           0  ...   
6          รัตติจันทร์พันกร              NaN        1031  ...   
13      นิ่งเฮียก็หาว่าซื่อ              NaN           0  ...   
11  เหนือมังกรเคียงบัลลังก์              NaN           0  ...   
8    เกิดใหม่ทั้งทีมีแค่นี้              NaN           0  ...   
9          ตัวนิดของคุณใหญ่              NaN           0  ...   
10                      NaN   เขาชื่ออันวาร์        1231  ...   
0                       NaN         เมกาโลมา          37  ...   
7                       NaN         อรุณรุ่ง          59  ...   
5                       NaN     ฉลามคลั่งรัก           0  ...   
12                      NaN       อุบายกินรา         268  ...   

    ratingNoTweet_q  ratingHashReview_q  ratingFav_q  ratingRT_q  \
14              3.0                 4.0          2.0         3.0   
3               1.0                 1.0          2.0         2.0   
4               1.0                 2.0          1.0